// packages/vue/src/components/ConfigProvider.vue
<script setup lang="ts">
import { provide, ref, watch, type Ref } from 'vue'
import type { IncremarkLocale } from '@incremark/shared'
import { zhCN } from '@incremark/shared'
import { LOCALE_KEY } from '../composables/useLocale'

interface Props {
  /** locale 对象 */
  locale?: IncremarkLocale
}

const props = withDefaults(defineProps<Props>(), {
  locale: () => zhCN
})

// 提供 locale 给子组件（确保不是 undefined）
const localeRef: Ref<IncremarkLocale> = ref(props.locale || zhCN)
provide(LOCALE_KEY, localeRef)

// 监听 locale 变化
watch(
  () => props.locale,
  (newLocale) => {
    if (newLocale) {
      localeRef.value = newLocale
    }
  },
  { deep: true }
)
</script>

<template>
  <slot />
</template>

// packages/svelte/src/components/ConfigProvider.svelte
<script lang="ts">
  import type { IncremarkLocale } from '@incremark/shared'
  import { zhCN } from '@incremark/shared'
  import { provideLocale } from '../stores/useLocale.svelte'

  interface Props {
    locale?: IncremarkLocale
    children: import('svelte').Snippet
  }

  // 提供 locale 给子组件（确保不是 undefined）
  const { locale, children }: Props = $props()

  // 在组件初始化时同步设置 context
  // 使用函数返回 locale 以支持响应式更新
  provideLocale(() => locale || zhCN)
</script>

{@render children()}
