// packages/react/src/components/IncremarkCodeMermaid.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react'
import type { Code } from 'mdast'
import { GravityMermaid, LucideCode, LucideEye, LucideCopy, LucideCopyCheck } from '@incremark/icons'
import { SvgIcon } from './SvgIcon'

export interface IncremarkCodeMermaidProps {
  node: Code
  /** Mermaid 渲染延迟（毫秒），用于流式输入时防抖 */
  mermaidDelay?: number
}

export const IncremarkCodeMermaid: React.FC<IncremarkCodeMermaidProps> = ({
  node,
  mermaidDelay = 500
}) => {
  const [copied, setCopied] = useState(false)
  const [mermaidSvg, setMermaidSvg] = useState('')
  const [mermaidLoading, setMermaidLoading] = useState(false)
  const [mermaidViewMode, setMermaidViewMode] = useState<'preview' | 'source'>('preview')

  const mermaidRef = useRef<any>(null)
  const mermaidTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const code = node.value

  const toggleMermaidView = useCallback(() => {
    setMermaidViewMode(prev => prev === 'preview' ? 'source' : 'preview')
  }, [])

  const copyCode = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // 复制失败静默处理
    }
  }, [code])

  const doRenderMermaid = useCallback(async () => {
    if (!code) return

    try {
      if (!mermaidRef.current) {
        const mermaidModule = await import('mermaid')
        mermaidRef.current = mermaidModule.default
        mermaidRef.current.initialize({
          startOnLoad: false,
          theme: 'dark',
          securityLevel: 'loose',
          suppressErrorRendering: true
        })
      }

      const mermaid = mermaidRef.current
      const id = `mermaid-${Date.now()}-${Math.random().toString(36).slice(2)}`
      const { svg } = await mermaid.render(id, code)
      setMermaidSvg(svg)
    } catch {
      setMermaidSvg('')
    } finally {
      setMermaidLoading(false)
    }
  }, [code])

  const scheduleRenderMermaid = useCallback(() => {
    if (!code) return

    if (mermaidTimerRef.current) {
      clearTimeout(mermaidTimerRef.current)
    }

    setMermaidLoading(true)
    mermaidTimerRef.current = setTimeout(() => {
      doRenderMermaid()
    }, mermaidDelay)
  }, [code, mermaidDelay, doRenderMermaid])

  useEffect(() => {
    scheduleRenderMermaid()
  }, [scheduleRenderMermaid])

  useEffect(() => {
    return () => {
      if (mermaidTimerRef.current) {
        clearTimeout(mermaidTimerRef.current)
      }
    }
  }, [])

  return (
    <div className="incremark-mermaid">
      <div className="mermaid-header">
        <span className="language">
          <SvgIcon svg={GravityMermaid} className="language-icon" />
          MERMAID
        </span>
        <div className="mermaid-actions">
          <button
            className="code-btn"
            onClick={toggleMermaidView}
            type="button"
            disabled={!mermaidSvg}
            title={mermaidViewMode === 'preview' ? 'View Source' : 'Preview'}
          >
            <SvgIcon svg={mermaidViewMode === 'preview' ? LucideCode : LucideEye} />
          </button>
          <button 
            className="code-btn" 
            onClick={copyCode} 
            type="button"
            title={copied ? 'Copied!' : 'Copy'}
          >
            <SvgIcon svg={copied ? LucideCopyCheck : LucideCopy} />
          </button>
        </div>
      </div>
      <div className="mermaid-content">
        {mermaidLoading && !mermaidSvg ? (
          <div className="mermaid-loading">
            <pre className="mermaid-source-code">{code}</pre>
          </div>
        ) : mermaidViewMode === 'source' ? (
          <pre className="mermaid-source-code">{code}</pre>
        ) : mermaidSvg ? (
          <div className="mermaid-svg" dangerouslySetInnerHTML={{ __html: mermaidSvg }} />
        ) : (
          <pre className="mermaid-source-code">{code}</pre>
        )}
      </div>
    </div>
  )
}

// packages/svelte/src/components/IncremarkCodeMermaid.svelte
<script lang="ts">
  import type { Code } from 'mdast'
  import { GravityMermaid, LucideCode, LucideEye, LucideCopy, LucideCopyCheck } from '@incremark/icons'
  import SvgIcon from './SvgIcon.svelte'

  /**
   * 组件 Props
   */
  interface Props {
    /** 代码节点 */
    node: Code
    /** Mermaid 渲染延迟（毫秒），用于流式输入时防抖 */
    mermaidDelay?: number
  }

  let {
    node,
    mermaidDelay = 500
  }: Props = $props()

  // 状态
  let copied = $state(false)
  let mermaidSvg = $state('')
  let mermaidLoading = $state(false)
  let mermaidRef: any = null
  let mermaidTimer: ReturnType<typeof setTimeout> | null = null
  let mermaidViewMode = $state<'preview' | 'source'>('preview')

  // 计算属性
  const code = $derived(node.value)

  /**
   * 切换 Mermaid 视图模式
   */
  function toggleMermaidView() {
    mermaidViewMode = mermaidViewMode === 'preview' ? 'source' : 'preview'
  }

  /**
   * 执行 Mermaid 渲染
   */
  async function doRenderMermaid() {
    if (!code) return

    try {
      if (!mermaidRef) {
        // @ts-ignore
        const mermaidModule = await import('mermaid')
        mermaidRef = mermaidModule.default
        mermaidRef.initialize({
          startOnLoad: false,
          theme: 'dark',
          securityLevel: 'loose',
          suppressErrorRendering: true
        })
      }

      const id = `mermaid-${Date.now()}-${Math.random().toString(36).slice(2)}`
      const { svg } = await mermaidRef.render(id, code)
      mermaidSvg = svg
    } catch (e: any) {
      mermaidSvg = ''
    } finally {
      mermaidLoading = false
    }
  }

  /**
   * 复制代码
   */
  async function copyCode() {
    try {
      await navigator.clipboard.writeText(code)
      copied = true
      setTimeout(() => { copied = false }, 2000)
    } catch { /* 静默处理 */ }
  }

  // 监听代码变化并重新渲染
  $effect(() => {
    // Mermaid 防抖逻辑
    if (mermaidTimer) clearTimeout(mermaidTimer)
    mermaidLoading = true
    mermaidTimer = setTimeout(doRenderMermaid, mermaidDelay)
    
    // 返回清理函数
    return () => {
      if (mermaidTimer) clearTimeout(mermaidTimer)
    }
  })
</script>

<div class="incremark-mermaid">
  <div class="mermaid-header">
    <span class="language">
      <SvgIcon svg={GravityMermaid} class="language-icon" />
      MERMAID
    </span>
    <div class="mermaid-actions">
      <button 
        class="code-btn" 
        onclick={toggleMermaidView} 
        type="button"
        disabled={!mermaidSvg}
        title={mermaidViewMode === 'preview' ? 'View Source' : 'Preview'}
      >
        <SvgIcon svg={mermaidViewMode === 'preview' ? LucideCode : LucideEye} />
      </button>
      <button 
        class="code-btn" 
        onclick={copyCode} 
        type="button"
        title={copied ? 'Copied!' : 'Copy'}
      >
        <SvgIcon svg={copied ? LucideCopyCheck : LucideCopy} />
      </button>
    </div>
  </div>
  <div class="mermaid-content">
    {#if mermaidLoading && !mermaidSvg}
      <pre class="mermaid-source-code">{code}</pre>
    {:else if mermaidViewMode === 'source'}
      <pre class="mermaid-source-code">{code}</pre>
    {:else if mermaidSvg}
      {@html mermaidSvg}
    {:else}
      <pre class="mermaid-source-code">{code}</pre>
    {/if}
  </div>
</div>
