// packages/solid/src/components/IncremarkContent.tsx
/* @jsxImportSource solid-js */

import { Component, createEffect, createMemo, onMount } from 'solid-js'
import type { JSX } from 'solid-js'
import { useIncremark } from '../composables/useIncremark'
import type { IncremarkContentProps } from '../types'
import Incremark from './Incremark'

/**
 * IncremarkContent 组件
 *
 * 全合一组件，自动处理流式和内容模式
 */
export const IncremarkContent: Component<IncremarkContentProps> = (props) => {
  const incremarkOptions = () => ({
    gfm: true,
    htmlTree: true,
    containers: true,
    math: true,
    ...props.incremarkOptions
  })

  const { blocks, append, finalize, render, reset, isDisplayComplete, markdown, contextValue, DefinationsProvider } = useIncremark(incremarkOptions)

  const isStreamMode = () => typeof props.stream === 'function'

  async function handleStreamInput() {
    if (!props.stream) return

    try {
      const stream = props.stream()

      for await (const chunk of stream) {
        append(chunk)
      }

      finalize()
    } catch (error) {
      console.error('Stream error: ', error)
      finalize()
    }
  }

  function handleContentInput(newContent?: string, oldContent?: string) {
    if (!newContent) {
      if (oldContent) {
        reset()
      }
      return
    }

    if (newContent?.startsWith(oldContent ?? '')) {
      const delta = newContent.slice((oldContent || '').length)
      append(delta)
    } else {
      render(newContent)
    }
  }

  // 监听 content 变化
  createEffect(() => {
    const newContent = props.content

    if (isStreamMode()) {
      handleStreamInput()
    } else {
      handleContentInput(newContent, markdown())
    }
  })

  // 监听 isFinished 变化
  createEffect(() => {
    const newIsFinished = props.isFinished
    if (newIsFinished && props.content === markdown()) {
      finalize()
    }
  })

  return (
    <DefinationsProvider value={contextValue}>
      <Incremark
        blocks={blocks}
        pendingClass={props.pendingClass}
        isDisplayComplete={isDisplayComplete()}
        showBlockStatus={props.showBlockStatus}
        components={props.components}
        customContainers={props.customContainers}
        customCodeBlocks={props.customCodeBlocks}
        codeBlockConfigs={props.codeBlockConfigs}
      />
    </DefinationsProvider>
  )
}

export default IncremarkContent

// packages/svelte/src/components/IncremarkContent.svelte
<!--
  @file IncremarkContent.svelte - 开箱即用的 Markdown 渲染组件
  @description 自动处理流式内容和普通内容的高级组件
-->

<script lang="ts">
  import { useIncremark, type UseIncremarkOptions } from '../stores/useIncremark'
  import type { IncremarkContentProps } from './types'
  import Incremark from './Incremark.svelte'
  import { get } from 'svelte/store'

  let {
    stream,
    content,
    components = {},
    customContainers = {},
    customCodeBlocks = {},
    codeBlockConfigs = {},
    isFinished = false,
    incremarkOptions,
    pendingClass = 'incremark-pending',
    showBlockStatus = false
  }: IncremarkContentProps = $props()

  // 合并默认选项（初始化时使用）
  const initialOptions: UseIncremarkOptions = {
    gfm: true,
    htmlTree: true,
    containers: true,
    math: true,
    ...incremarkOptions
  }

  const { blocks, append, finalize, render, reset, isDisplayComplete, markdown, typewriter } = useIncremark(initialOptions)

  // 监听 incremarkOptions 的变化，更新 typewriter 配置
  $effect(() => {
    if (incremarkOptions?.typewriter) {
      typewriter.setOptions(incremarkOptions.typewriter)
    }
  })

  // 派生状态
  const isStreamMode = $derived(typeof stream === 'function')

  // 保存前一个 content 值用于增量更新
  let prevContent: string | undefined = $state(undefined)
  let isStreaming = $state(false)

  async function handleStreamInput() {
    if (!stream || isStreaming) return

    isStreaming = true
    try {
      const streamGen = stream()

      for await (const chunk of streamGen) {
        append(chunk)
      }

      finalize()
    } catch (error) {
      console.error('Stream error: ', error)
      finalize()
    } finally {
      isStreaming = false
    }
  }

  function handleContentInput(newContent?: string, oldContent?: string) {
    if (!newContent) {
      if (oldContent) {
        reset()
      }
      return
    }

    if (newContent?.startsWith(oldContent ?? '')) {
      const delta = newContent.slice((oldContent || '').length)
      append(delta)
    } else {
      render(newContent)
    }
  }

  // 监听 content 变化
  $effect(() => {
    if (isStreamMode) {
      handleStreamInput()
    } else {
      handleContentInput(content, prevContent)
    }
    prevContent = content
  })

  // 监听 isFinished 变化
  $effect(() => {
    if (isFinished && content === get(markdown)) {
      finalize()
    }
  })
</script>

<Incremark
  blocks={$blocks}
  isDisplayComplete={$isDisplayComplete}
  {pendingClass}
  {showBlockStatus}
  {components}
  {customContainers}
  {customCodeBlocks}
  {codeBlockConfigs}
/>
