// examples/react/src/components/CustomInfoContainer.tsx
import React from 'react'

export interface CustomInfoContainerProps {
  name: string
  options?: Record<string, any>
  children?: React.ReactNode
}

export const CustomInfoContainer: React.FC<CustomInfoContainerProps> = ({ options, children }) => {
  return (
    <div className="custom-info-container">
      <div className="custom-info-header">
        <span className="custom-info-icon">ℹ️</span>
        <span className="custom-info-title">
          {options?.title || '信息'}
        </span>
      </div>
      <div className="custom-info-content">
        {children}
      </div>
    </div>
  )
}

// examples/svelte/src/components/CustomInfoContainer.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    name: string
    options?: Record<string, any>
    children?: Snippet;
  }

  let { options, children }: Props = $props()
</script>

<div class="custom-info-container">
  <div class="custom-info-header">
    <span class="custom-info-icon">ℹ️</span>
    <span class="custom-info-title">
      {options?.title || '信息'}
    </span>
  </div>
  <div class="custom-info-content">
    {#if children}
      {@render children()}
    {/if}
  </div>
</div>
