// examples/react/src/components/CustomTipContainer.tsx
import React from 'react'

export interface CustomTipContainerProps {
  name: string
  options?: Record<string, any>
  children?: React.ReactNode
}

export const CustomTipContainer: React.FC<CustomTipContainerProps> = ({ options, children }) => {
  return (
    <div className="custom-tip-container">
      <div className="custom-tip-header">
        <span className="custom-tip-icon">💡</span>
        <span className="custom-tip-title">
          {options?.title || '提示'}
        </span>
      </div>
      <div className="custom-tip-content">
        {children}
      </div>
    </div>
  )
}

// examples/svelte/src/components/CustomTipContainer.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  
  interface Props {
    name: string
    options?: Record<string, any>
    children?: Snippet;
  }

  let { options, children }: Props = $props()
</script>

<div class="custom-tip-container">
  <div class="custom-tip-header">
    <span class="custom-tip-icon">💡</span>
    <span class="custom-tip-title">
      {options?.title || '提示'}
    </span>
  </div>
  <div class="custom-tip-content">
    {#if children}
      {@render children()}
    {/if}
  </div>
</div>
