// examples/react/src/components/CustomTipContainer.tsx
import React from 'react'

export interface CustomTipContainerProps {
  name: string
  options?: Record<string, any>
  children?: React.ReactNode
}

export const CustomTipContainer: React.FC<CustomTipContainerProps> = ({ options, children }) => {
  return (
    <div className="custom-tip-container">
      <div className="custom-tip-header">
        <span className="custom-tip-icon">💡</span>
        <span className="custom-tip-title">
          {options?.title || '提示'}
        </span>
      </div>
      <div className="custom-tip-content">
        {children}
      </div>
    </div>
  )
}

// examples/vue/src/components/CustomTipContainer.vue
<script setup lang="ts">
defineProps<{
  name: string
  options?: Record<string, any>
}>()
</script>

<template>
  <div class="custom-tip-container">
    <div class="custom-tip-header">
      <span class="custom-tip-icon">💡</span>
      <span v-if="options?.title" class="custom-tip-title">{{ options.title }}</span>
      <span v-else class="custom-tip-title">提示</span>
    </div>
    <div class="custom-tip-content">
      <slot />
    </div>
  </div>
</template>

<!-- 样式已移动到共享的 styles.css -->
