// examples/react/src/components/CustomWarningContainer.tsx
import React from 'react'

export interface CustomWarningContainerProps {
  name: string
  options?: Record<string, any>
  children?: React.ReactNode
}

export const CustomWarningContainer: React.FC<CustomWarningContainerProps> = ({ options, children }) => {
  return (
    <div className="custom-warning-container">
      <div className="custom-warning-header">
        <span className="custom-warning-icon">⚠️</span>
        <span className="custom-warning-title">
          {options?.title || '警告'}
        </span>
      </div>
      <div className="custom-warning-content">
        {children}
      </div>
    </div>
  )
}

// examples/vue/src/components/CustomWarningContainer.vue
<script setup lang="ts">
defineProps<{
  name: string
  options?: Record<string, any>
}>()
</script>

<template>
  <div class="custom-warning-container">
    <div class="custom-warning-header">
      <span class="custom-warning-icon">⚠️</span>
      <span v-if="options?.title" class="custom-warning-title">{{ options.title }}</span>
      <span v-else class="custom-warning-title">警告</span>
    </div>
    <div class="custom-warning-content">
      <slot />
    </div>
  </div>
</template>

<!-- 样式已移动到共享的 styles.css -->
