// examples/solid/src/components/IncremarkDemo.tsx
/* @jsxImportSource solid-js */

import {
  createSignal,
  createEffect,
  Show
} from 'solid-js'
import { MicromarkAstBuilder } from '@incremark/core/engines/micromark'
import {
  IncremarkContent,
  AutoScrollContainer,
  ThemeProvider,
  ConfigProvider,
  type DesignTokens,
  type UseIncremarkOptions,
  type IncremarkLocale
} from '@incremark/solid'
import { CustomHeading, CustomWarningContainer, CustomInfoContainer, CustomTipContainer, BenchmarkPanel, CustomInputPanel, type BenchmarkStats } from './index'
import { CustomEchartCodeBlock } from './CustomEchartCodeBlock'
import type { Messages } from '../hooks/useLocale'
import type { IncremarkDevTools } from '@incremark/devtools'

export interface IncremarkDemoProps {
  htmlEnabled: boolean
  sampleMarkdown: string
  t: Messages
  locale?: IncremarkLocale
  devtools?: IncremarkDevTools | null
}

// ============ 自定义容器 ============
const customContainers = {
  warning: CustomWarningContainer,
  info: CustomInfoContainer,
  tip: CustomTipContainer
}

// ============ 自定义组件 ============
const customComponents = { heading: CustomHeading }

// ============ 主题系统 ============
function createThemeSignals() {
  const [themeMode, setThemeMode] = createSignal<'default' | 'dark' | 'custom'>('default')

  const customThemeOverride: Partial<DesignTokens> = {
    color: {
      brand: {
        primary: '#8b5cf6',
        primaryHover: '#7c3aed',
        primaryActive: '#6d28d9',
        primaryLight: '#a78bfa'
      }
    } as any
  }

  const currentTheme = () => {
    switch (themeMode()) {
      case 'dark':
        return 'dark'
      case 'custom':
        return customThemeOverride
      default:
        return 'default'
    }
  }

  return { themeMode, setThemeMode, currentTheme }
}

export function IncremarkDemo(props: IncremarkDemoProps) {
  const theme = createThemeSignals()

  // ============ 自定义代码块配置（放在函数内避免循环依赖）============
  const customCodeBlocks = {
    echarts: CustomEchartCodeBlock,
  }

  const codeBlockConfigs = {
    echarts: {
      takeOver: true,
    }
  }

  // ============ 打字机配置 ============
  const [typewriterEnabled, setTypewriterEnabled] = createSignal(false)
  const [typewriterSpeed, setTypewriterSpeed] = createSignal(2)
  const [typewriterInterval, setTypewriterInterval] = createSignal(30)
  const [typewriterRandomStep, setTypewriterRandomStep] = createSignal(true)
  const [typewriterEffect, setTypewriterEffect] = createSignal<'none' | 'fade-in' | 'typing'>('typing')

  // ============ 数学公式配置 ============
  const [mathTexEnabled, setMathTexEnabled] = createSignal(false)

  // ============ 引擎配置 ============
  const [engineType, setEngineType] = createSignal<'marked' | 'micromark'>('marked')

  // ============ 内容状态 ============
  const [mdContent, setMdContent] = createSignal('')
  const [isFinished, setIsFinished] = createSignal(false)

  // ============ 流式输出 ============
  const [isStreaming, setIsStreaming] = createSignal(false)

  // ============ 自动滚动 ============
  const [autoScrollEnabled, setAutoScrollEnabled] = createSignal(true)

  // ============ 自定义输入 ============
  const [customInputMode, setCustomInputMode] = createSignal(false)
  const [customMarkdown, setCustomMarkdown] = createSignal('')

  // ============ 自定义组件开关 ============
  const [useCustomComponents, setUseCustomComponents] = createSignal(false)

  // ============ Benchmark ============
  const [benchmarkMode, setBenchmarkMode] = createSignal(false)
  const [benchmarkRunning, setBenchmarkRunning] = createSignal(false)
  const [benchmarkProgress, setBenchmarkProgress] = createSignal(0)
  const [benchmarkStats, setBenchmarkStats] = createSignal<BenchmarkStats>({
    traditional: { time: 0, parseCount: 0, totalChars: 0 },
    incremark: { time: 0, parseCount: 0, totalChars: 0 }
  })

  // ============ Incremark 配置（响应式） ============
  const incremarkOptions = () => ({
    gfm: true,
    math: mathTexEnabled() ? { tex: true } : true,
    htmlTree: props.htmlEnabled,
    containers: true,
    astBuilder: engineType() === 'micromark' ? MicromarkAstBuilder : undefined,
    typewriter: {
      enabled: typewriterEnabled(),
      charsPerTick: typewriterRandomStep()
        ? [1, Math.max(2, typewriterSpeed())] as [number, number]
        : typewriterSpeed(),
      tickInterval: typewriterInterval(),
      effect: typewriterEffect(),
      cursor: '|'
    }
  })

  async function simulateStream() {
    setMdContent('')
    setIsFinished(false)
    setIsStreaming(true)

    await new Promise(resolve => setTimeout(resolve, 0))

    const content = customInputMode() && customMarkdown().trim()
      ? customMarkdown()
      : props.sampleMarkdown
    const chunks = content.match(/[\s\S]{1,20}/g) || []

    // 性能监测
    const updateTimes: number[] = []
    console.log(`[Perf] Starting stream with ${chunks.length} chunks`)

    for (const chunk of chunks) {
      const start = performance.now()
      setMdContent(prev => prev + chunk)
      const elapsed = performance.now() - start
      updateTimes.push(elapsed)
      await new Promise(resolve => setTimeout(resolve, 30))
    }

    // 输出性能统计
    const avg = updateTimes.reduce((a, b) => a + b, 0) / updateTimes.length
    const max = Math.max(...updateTimes)
    const min = Math.min(...updateTimes)
    console.log(`[Perf] Stream completed:`)
    console.log(`  - Chunks: ${chunks.length}`)
    console.log(`  - Avg update: ${avg.toFixed(2)}ms`)
    console.log(`  - Min update: ${min.toFixed(2)}ms`)
    console.log(`  - Max update: ${max.toFixed(2)}ms`)
    console.log(`  - Updates > 16ms (frame drop): ${updateTimes.filter(t => t > 16).length}`)

    setIsFinished(true)
    setIsStreaming(false)
  }

  function renderOnce() {
    const content = customInputMode() && customMarkdown().trim()
      ? customMarkdown()
      : props.sampleMarkdown
    setMdContent(content)
    setIsFinished(true)
  }

  function reset() {
    setMdContent('')
    setIsFinished(false)
  }

  async function handleRunBenchmark() {
    const content = customInputMode() && customMarkdown().trim()
      ? customMarkdown()
      : props.sampleMarkdown

    setBenchmarkRunning(true)
    setBenchmarkProgress(0)

    const chunks = content.match(/[\s\S]{1,20}/g) || []

    // 1. 测试传统方式：模拟每次重新渲染
    let traditionalTime = 0
    let traditionalParseCount = 0
    let traditionalTotalChars = 0
    let accumulated = ''

    for (let i = 0; i < chunks.length; i++) {
      accumulated += chunks[i]
      const start = performance.now()
      // 模拟传统方式：每次都重新设置完整内容
      setMdContent(accumulated)
      traditionalTime += performance.now() - start
      traditionalParseCount++
      traditionalTotalChars += accumulated.length
      setBenchmarkProgress(((i + 1) / chunks.length) * 50)
      await new Promise(r => setTimeout(r, 5))
    }

    // 2. 测试增量方式
    setMdContent('')
    setIsFinished(false)
    let incremarkTime = 0
    let incremarkParseCount = 0
    let incremarkTotalChars = 0

    for (let i = 0; i < chunks.length; i++) {
      const start = performance.now()
      setMdContent(prev => prev + chunks[i])
      incremarkTime += performance.now() - start
      incremarkParseCount++
      incremarkTotalChars += chunks[i].length
      setBenchmarkProgress(50 + ((i + 1) / chunks.length) * 50)
      await new Promise(r => setTimeout(r, 5))
    }

    setIsFinished(true)

    setBenchmarkStats({
      traditional: { time: traditionalTime, parseCount: traditionalParseCount, totalChars: traditionalTotalChars },
      incremark: { time: incremarkTime, parseCount: incremarkParseCount, totalChars: incremarkTotalChars }
    })

    setBenchmarkRunning(false)
  }

  // ============ 解析器配置变化时重置内容 ============
  createEffect(() => {
    engineType()
    mathTexEnabled()
    reset()
  })

  return (
    <div class="demo-content">
      <div class="controls">
        <button onClick={simulateStream} disabled={isStreaming() || benchmarkRunning()}>
          {isStreaming() ? props.t.streaming : props.t.simulateAI}
        </button>
        <button onClick={renderOnce} disabled={isStreaming() || benchmarkRunning()}>
          {props.t.renderOnce}
        </button>
        <button onClick={reset} disabled={isStreaming() || benchmarkRunning()}>
          {props.t.reset}
        </button>

        <label class="checkbox">
          <input
            type="checkbox"
            checked={useCustomComponents()}
            onChange={(e) => setUseCustomComponents(e.currentTarget.checked)}
          />
          {props.t.customComponents}
        </label>
        <label class="checkbox benchmark-toggle">
          <input
            type="checkbox"
            checked={benchmarkMode()}
            onChange={(e) => setBenchmarkMode(e.currentTarget.checked)}
          />
          {props.t.benchmarkMode}
        </label>
        <label class="checkbox">
          <input
            type="checkbox"
            checked={customInputMode()}
            onChange={(e) => setCustomInputMode(e.currentTarget.checked)}
          />
          {props.t.customInput}
        </label>
        <label class="checkbox typewriter-toggle">
          <input
            type="checkbox"
            checked={typewriterEnabled()}
            onChange={(e) => setTypewriterEnabled(e.currentTarget.checked)}
          />
          {props.t.typewriterMode}
        </label>
        <label class="checkbox auto-scroll-toggle">
          <input
            type="checkbox"
            checked={autoScrollEnabled()}
            onChange={(e) => setAutoScrollEnabled(e.currentTarget.checked)}
          />
          {props.t.autoScroll}
        </label>
        <label class="checkbox tex-toggle" title={props.t.texTooltip}>
          <input
            type="checkbox"
            checked={mathTexEnabled()}
            onChange={(e) => setMathTexEnabled(e.currentTarget.checked)}
          />
          {props.t.mathTex}
        </label>

        <select
          value={engineType()}
          onChange={(e) => setEngineType(e.currentTarget.value as any)}
          class="engine-select"
          title={props.t.engineTooltip}
        >
          <option value="marked">{props.t.engineMarked}</option>
          <option value="micromark">{props.t.engineMicromark}</option>
        </select>

        <select
          value={theme.themeMode()}
          onChange={(e) => theme.setThemeMode(e.currentTarget.value as any)}
          class="theme-select"
        >
          <option value="default">Light Theme</option>
          <option value="dark">Dark Theme</option>
          <option value="custom">Custom Theme</option>
        </select>

        <Show when={typewriterEnabled()}>
          <label class="speed-control">
            <input
              type="range"
              min="1"
              max="10"
              step="1"
              value={typewriterSpeed()}
              onInput={(e) => setTypewriterSpeed(parseInt(e.currentTarget.value))}
            />
            <span class="speed-value">
              {typewriterSpeed()} {props.t.charsPerTick}
            </span>
          </label>
          <label class="speed-control">
            <input
              type="range"
              min="10"
              max="200"
              step="10"
              value={typewriterInterval()}
              onInput={(e) => setTypewriterInterval(parseInt(e.currentTarget.value))}
            />
            <span class="speed-value">
              {typewriterInterval()} {props.t.intervalMs}
            </span>
          </label>
          <label class="checkbox random-step-toggle">
            <input
              type="checkbox"
              checked={typewriterRandomStep()}
              onChange={(e) => setTypewriterRandomStep(e.currentTarget.checked)}
            />
            {props.t.randomStep}
          </label>
          <select
            value={typewriterEffect()}
            onChange={(e) => setTypewriterEffect(e.currentTarget.value as any)}
            class="effect-select"
          >
            <option value="none">{props.t.effectNone}</option>
            <option value="fade-in">{props.t.effectFadeIn}</option>
            <option value="typing">{props.t.effectTyping}</option>
          </select>
        </Show>

        <span class="stats">
          {mdContent().length} {props.t.chars}
        </span>
      </div>

      <Show when={benchmarkMode()}>
        <BenchmarkPanel
          stats={benchmarkStats()}
          running={benchmarkRunning()}
          progress={benchmarkProgress()}
          t={props.t}
          onRun={handleRunBenchmark}
        />
      </Show>

      <Show when={customInputMode()}>
        <CustomInputPanel
          value={customMarkdown()}
          t={props.t}
          onChange={setCustomMarkdown}
          onUseExample={() => setCustomMarkdown(props.sampleMarkdown)}
        />
      </Show>

      <main class={`content ${typewriterEnabled() ? `effect-${typewriterEffect()}` : ''}`}>
        <ConfigProvider locale={props.locale}>
          <ThemeProvider theme={theme.currentTheme()}>
            <AutoScrollContainer enabled={autoScrollEnabled()} class="scroll-container">
              <IncremarkContent
                content={mdContent()}
                isFinished={isFinished()}
                incremarkOptions={incremarkOptions()}
                components={useCustomComponents() ? customComponents : {}}
                customContainers={customContainers}
                customCodeBlocks={customCodeBlocks}
                codeBlockConfigs={codeBlockConfigs}
                showBlockStatus={true}
                devtools={props.devtools ?? undefined}
              />
            </AutoScrollContainer>
          </ThemeProvider>
        </ConfigProvider>
      </main>
    </div>
  )
}

// examples/vue/src/components/IncremarkDemo.vue
<script setup lang="ts">
import { ref, computed, nextTick, watch } from 'vue'
import { IncremarkContent, AutoScrollContainer, ThemeProvider, ConfigProvider, type DesignTokens, type UseIncremarkOptions, type IncremarkLocale } from '@incremark/vue'
import { MicromarkAstBuilder } from '@incremark/core/engines/micromark'
import type { IncremarkDevTools } from '@incremark/devtools'

import { BenchmarkPanel, CustomInputPanel, CustomHeading, CustomWarningContainer, CustomInfoContainer, CustomTipContainer, CustomEchartCodeBlock } from './index'
import type { BenchmarkStats } from '../composables'
import type { Messages } from '../locales'

const props = defineProps<{
  htmlEnabled: boolean
  sampleMarkdown: string
  t: Messages
  locale?: IncremarkLocale
  devtools?: IncremarkDevTools
}>()

// ============ 打字机配置 ============
const typewriterEnabled = ref(false)
const typewriterSpeed = ref(2)
const typewriterInterval = ref(30)
const typewriterRandomStep = ref(true)
const typewriterEffect = ref<'none' | 'fade-in' | 'typing'>('typing')

// ============ 数学公式配置 ============
const mathTexEnabled = ref(false)

// ============ 引擎配置 ============
const engineType = ref<'marked' | 'micromark'>('marked')

// ============ 内容状态 ============
const mdContent = ref('')
const isFinished = ref(false)

// ============ Incremark 配置（响应式） ============
const incremarkOptions = computed<UseIncremarkOptions>(() => ({
  gfm: true,
  math: mathTexEnabled.value ? { tex: true } : true,
  htmlTree: props.htmlEnabled,
  containers: true,
  astBuilder: engineType.value === 'micromark' ? MicromarkAstBuilder : undefined,
  typewriter: {
    enabled: typewriterEnabled.value,
    charsPerTick: typewriterRandomStep.value
      ? [1, Math.max(2, typewriterSpeed.value)] as [number, number]
      : typewriterSpeed.value,
    tickInterval: typewriterInterval.value,
    effect: typewriterEffect.value,
    cursor: '|'
  }
}))

// ============ 流式输出 ============
const isStreaming = ref(false)

async function simulateStream() {
  mdContent.value = ''
  isFinished.value = false
  isStreaming.value = true

  await nextTick();

  const content = customInputMode.value && customMarkdown.value.trim()
    ? customMarkdown.value
    : props.sampleMarkdown
  const chunks = content.match(/[\s\S]{1,20}/g) || []

  // 性能监测
  const updateTimes: number[] = []
  console.log(`[Perf] Starting stream with ${chunks.length} chunks`)

  for (const chunk of chunks) {
    const start = performance.now()
    mdContent.value += chunk
    await nextTick() // 等待 DOM 更新完成
    const elapsed = performance.now() - start
    updateTimes.push(elapsed)
    await new Promise((resolve) => setTimeout(resolve, 30))
  }

  // 输出性能统计
  const avg = updateTimes.reduce((a, b) => a + b, 0) / updateTimes.length
  const max = Math.max(...updateTimes)
  const min = Math.min(...updateTimes)
  console.log(`[Perf] Stream completed:`)
  console.log(`  - Chunks: ${chunks.length}`)
  console.log(`  - Avg update: ${avg.toFixed(2)}ms`)
  console.log(`  - Min update: ${min.toFixed(2)}ms`)
  console.log(`  - Max update: ${max.toFixed(2)}ms`)
  console.log(`  - Updates > 16ms (frame drop): ${updateTimes.filter(t => t > 16).length}`)

  isFinished.value = true
  isStreaming.value = false
}

function renderOnce() {
  const content = customInputMode.value && customMarkdown.value.trim()
    ? customMarkdown.value
    : props.sampleMarkdown
  mdContent.value = content
  isFinished.value = true
}

function reset() {
  mdContent.value = ''
  isFinished.value = false
}

// ============ 解析器配置变化时重置内容 ============
// 当引擎或 math 配置变化时，重置 demo 的本地状态
watch([engineType, mathTexEnabled], () => {
  reset()
})

// ============ 自动滚动 ============
const autoScrollEnabled = ref(true)

// ============ 自定义输入 ============
const customInputMode = ref(false)
const customMarkdown = ref('')

// ============ Benchmark ============
const benchmarkMode = ref(false)
const benchmarkRunning = ref(false)
const benchmarkProgress = ref(0)
const benchmarkStats = ref<BenchmarkStats>({
  traditional: { time: 0, parseCount: 0, totalChars: 0 },
  incremark: { time: 0, parseCount: 0, totalChars: 0 }
})

async function handleRunBenchmark() {
  const content = customInputMode.value && customMarkdown.value.trim()
    ? customMarkdown.value
    : props.sampleMarkdown

  benchmarkRunning.value = true
  benchmarkProgress.value = 0

  const chunks = content.match(/[\s\S]{1,20}/g) || []

  // 1. 测试传统方式：模拟每次重新渲染
  let traditionalTime = 0
  let traditionalParseCount = 0
  let traditionalTotalChars = 0
  let accumulated = ''

  for (let i = 0; i < chunks.length; i++) {
    accumulated += chunks[i]
    const start = performance.now()
    // 模拟传统方式：每次都重新设置完整内容
    mdContent.value = accumulated
    traditionalTime += performance.now() - start
    traditionalParseCount++
    traditionalTotalChars += accumulated.length
    benchmarkProgress.value = ((i + 1) / chunks.length) * 50
    await new Promise(r => setTimeout(r, 5))
  }

  // 2. 测试增量方式
  mdContent.value = ''
  isFinished.value = false
  let incremarkTime = 0
  let incremarkParseCount = 0
  let incremarkTotalChars = 0

  for (let i = 0; i < chunks.length; i++) {
    const start = performance.now()
    mdContent.value += chunks[i]
    incremarkTime += performance.now() - start
    incremarkParseCount++
    incremarkTotalChars += chunks[i].length
    benchmarkProgress.value = 50 + ((i + 1) / chunks.length) * 50
    await new Promise(r => setTimeout(r, 5))
  }

  isFinished.value = true

  benchmarkStats.value = {
    traditional: { time: traditionalTime, parseCount: traditionalParseCount, totalChars: traditionalTotalChars },
    incremark: { time: incremarkTime, parseCount: incremarkParseCount, totalChars: incremarkTotalChars }
  }

  benchmarkRunning.value = false
}

// ============ 自定义组件 ============
const useCustomComponents = ref(false)
const customComponents = { heading: CustomHeading }

// ============ 自定义容器 ============
const customContainers = {
  warning: CustomWarningContainer,
  info: CustomInfoContainer,
  tip: CustomTipContainer,
}

// ============ 自定义代码块 ============
const customCodeBlocks = {
  echarts: CustomEchartCodeBlock,
}

// ============ 代码块配置 ============
const codeBlockConfigs = {
  echarts: {
    takeOver: true,
  }
}

// ============ 主题系统 ============
const themeMode = ref<'default' | 'dark' | 'custom'>('default')

const customThemeOverride: Partial<DesignTokens> = {
  color: {
    brand: {
      primary: '#8b5cf6',
      primaryHover: '#7c3aed',
      primaryActive: '#6d28d9',
      primaryLight: '#a78bfa'
    }
  } as any
}

const currentTheme = computed<'default' | 'dark' | DesignTokens | Partial<DesignTokens>>(() => {
  switch (themeMode.value) {
    case 'dark':
      return 'dark'
    case 'custom':
      return customThemeOverride
    default:
      return 'default'
  }
})

// 暴露方法供父组件调用
defineExpose({
  reset,
  renderOnce,
  mdContent,
  isStreaming,
  benchmarkRunning
})
</script>

<template>
  <div class="demo-content">
    <div class="controls">
      <button @click="simulateStream" :disabled="isStreaming || benchmarkRunning">
        {{ isStreaming ? t.streaming : t.simulateAI }}
      </button>
      <button @click="renderOnce" :disabled="isStreaming || benchmarkRunning">{{ t.renderOnce }}</button>
      <button @click="reset" :disabled="isStreaming || benchmarkRunning">{{ t.reset }}</button>

      <label class="checkbox">
        <input type="checkbox" v-model="useCustomComponents" />
        {{ t.customComponents }}
      </label>
      <label class="checkbox benchmark-toggle">
        <input type="checkbox" v-model="benchmarkMode" />
        {{ t.benchmarkMode }}
      </label>
      <label class="checkbox">
        <input type="checkbox" v-model="customInputMode" />
        {{ t.customInput }}
      </label>
      <label class="checkbox typewriter-toggle">
        <input type="checkbox" v-model="typewriterEnabled" />
        {{ t.typewriterMode }}
      </label>
      <label class="checkbox auto-scroll-toggle">
        <input type="checkbox" v-model="autoScrollEnabled" />
        {{ t.autoScroll }}
      </label>
      <label class="checkbox tex-toggle" :title="t.texTooltip">
        <input type="checkbox" v-model="mathTexEnabled" />
        {{ t.mathTex }}
      </label>

      <select v-model="engineType" class="engine-select" :title="t.engineTooltip">
        <option value="marked">{{ t.engineMarked }}</option>
        <option value="micromark">{{ t.engineMicromark }}</option>
      </select>

      <select v-model="themeMode" class="theme-select">
        <option value="default">Light Theme</option>
        <option value="dark">Dark Theme</option>
        <option value="custom">Custom Theme</option>
      </select>

      <template v-if="typewriterEnabled">
        <label class="speed-control">
          <input type="range" v-model.number="typewriterSpeed" min="1" max="10" step="1" />
          <span class="speed-value">{{ typewriterSpeed }} {{ t.charsPerTick }}</span>
        </label>
        <label class="speed-control">
          <input type="range" v-model.number="typewriterInterval" min="10" max="200" step="10" />
          <span class="speed-value">{{ typewriterInterval }} {{ t.intervalMs }}</span>
        </label>
        <label class="checkbox random-step-toggle">
          <input type="checkbox" v-model="typewriterRandomStep" />
          {{ t.randomStep }}
        </label>
        <select v-model="typewriterEffect" class="effect-select">
          <option value="none">{{ t.effectNone }}</option>
          <option value="fade-in">{{ t.effectFadeIn }}</option>
          <option value="typing">{{ t.effectTyping }}</option>
        </select>
      </template>

      <span class="stats">
        {{ mdContent.length }} {{ t.chars }}
      </span>
    </div>

    <BenchmarkPanel
      v-if="benchmarkMode"
      :stats="benchmarkStats"
      :running="benchmarkRunning"
      :progress="benchmarkProgress"
      :t="t"
      @run="handleRunBenchmark"
    />

    <CustomInputPanel
      v-if="customInputMode"
      v-model="customMarkdown"
      :t="t"
      @use-example="customMarkdown = sampleMarkdown"
    />

    <main :class="['content', typewriterEnabled && `effect-${typewriterEffect}`]">
      <ConfigProvider :locale="locale">
        <ThemeProvider :theme="currentTheme">
          <AutoScrollContainer :enabled="autoScrollEnabled" class="scroll-container">
            <IncremarkContent
              :content="mdContent"
              :is-finished="isFinished"
              :incremark-options="incremarkOptions"
              :components="useCustomComponents ? customComponents : {}"
              :custom-containers="customContainers"
              :custom-code-blocks="customCodeBlocks"
              :code-block-configs="codeBlockConfigs"
              :show-block-status="true"
              :devtools="devtools"
            />
          </AutoScrollContainer>
        </ThemeProvider>
      </ConfigProvider>
    </main>
  </div>
</template>
