// packages/solid/src/components/CachedCodeRenderer.tsx
/* @jsxImportSource solid-js */

/**
 * CachedCodeRenderer - 使用 shiki-stream 实现流式代码高亮
 *
 * 基于 shiki-stream 的 SolidJS 实现，参考 Vue/React 版本
 *
 * 与 Vue/React 版本保持一致：
 * - 在组件初始化时创建 stream（不在 onMount 中）
 * - 直接消费 stream，不使用单独的 Renderer 组件
 * - hasStreamError 状态和错误处理
 * - class: 'shiki incremark-code-stream'
 */
import type { ThemedToken } from '@shikijs/core'
import { CodeToTokenTransformStream } from 'shiki-stream'
import { getTokenStyleObject } from '@shikijs/core'
import { createEffect, createSignal, on, onCleanup, onMount, For, Show } from 'solid-js'
import { batch } from 'solid-js'
import { Component } from 'solid-js'

export interface CachedCodeRendererProps {
  code: string
  lang: string
  theme: string
  highlighter: any
  onStreamStart?: () => void
  onStreamEnd?: () => void
  onStreamError?: () => void
}

// SSR 检测：Web Streams API 只在浏览器中可用
const isBrowser = typeof window !== 'undefined'

export const CachedCodeRenderer: Component<CachedCodeRendererProps> = (props) => {
  // Stream 错误状态
  const [hasStreamError, setHasStreamError] = createSignal(false)

  // Tokens 数组 - 使用 reactive 模式（与 Vue 一致）
  const [tokens, setTokens] = createSignal<ThemedToken[]>([])

  // Stream 相关状态（只在浏览器中初始化）
  const [index, setIndex] = createSignal(0)
  let controller: ReadableStreamController<string> | null = null
  let abortController: AbortController | null = null

  // 只在浏览器环境中创建 stream（在 onMount 中，确保只执行一次）
  // 这是与 Vue 版本的关键区别：Vue 的 setup 只执行一次，SolidJS 组件函数可能执行多次
  // 所以使用 onMount 来确保 stream 只创建一次
  onMount(() => {
    if (!isBrowser) return

    const textStream = new ReadableStream<string>({
      start(_controller) {
        controller = _controller
      },
    })

    try {
      const tokenStream = textStream.pipeThrough(
        new CodeToTokenTransformStream({
          highlighter: props.highlighter,
          lang: props.lang,
          theme: props.theme,
          allowRecalls: true,
        })
      )

      // 消费 stream（与 Vue 版本对齐，直接消费）
      let started = false

      abortController = new AbortController()

      tokenStream.pipeTo(new WritableStream({
        write(token) {
          if (abortController?.signal.aborted) return

          if (!started) {
            started = true
            props.onStreamStart?.()
          }

          batch(() => {
            if ('recall' in token) {
              // 处理 recall：删除最后 N 个 tokens
              setTokens(ts => ts.slice(0, -token.recall))
            } else {
              // 添加新 token
              setTokens(ts => [...ts, token])
            }
          })
        },
        close: () => {
          if (!abortController?.signal.aborted) {
            props.onStreamEnd?.()
          }
        },
        abort: () => {
          if (!abortController?.signal.aborted) {
            props.onStreamEnd?.()
          }
        },
      }), { signal: abortController.signal }).catch((error) => {
        // Ignore abort errors (normal cleanup)
        if (error instanceof Error && error.name === 'AbortError') {
          return
        }
        // 静默处理不支持的语言错误（不打印到 console）
        if (error instanceof Error && error.message.includes('not found')) {
          setHasStreamError(true)
          return
        }
        console.error('Stream error:', error)
        setHasStreamError(true)
      })
    } catch (error) {
      // 静默处理不支持的语言错误（不打印到 console）
      if (error instanceof Error && error.message.includes('not found')) {
        setHasStreamError(true)
        return
      }
      console.error('Failed to create token stream:', error)
      setHasStreamError(true)
    }
  })

  // 监听 code 变化，增量推送到流中（使用 on 进行精确追踪）
  createEffect(on(
    () => props.code,
    (newCode) => {
      if (!isBrowser || !controller || abortController?.signal.aborted) return

      // 只处理增量更新：传入新增的部分
      const currentIndex = index()
      if (newCode.length > currentIndex && !hasStreamError()) {
        const incremental = newCode.slice(currentIndex)
        controller.enqueue(incremental as any)
        setIndex(newCode.length)
      }
    },
  ))

  // 组件卸载时清理
  onCleanup(() => {
    abortController?.abort()
    controller = null
    setHasStreamError(false)
    setTokens([])
    setIndex(0)
  })

  // 渲染（与 Vue/React 版本对齐）
  return (
    <Show
      when={!(hasStreamError() || !isBrowser || tokens().length === 0)}
      fallback={
        // SSR 或错误时渲染原始代码
        <pre class="shiki incremark-code-stream">
          <code>{props.code}</code>
        </pre>
      }
    >
      {/* 正常渲染高亮代码 */}
      <pre class="shiki incremark-code-stream">
        <code>
          <For each={tokens()}>
            {(token) => (
              <span style={token.htmlStyle ?? getTokenStyleObject(token)}>
                {token.content}
              </span>
            )}
          </For>
        </code>
      </pre>
    </Show>
  )
}

// packages/react/src/components/CachedCodeRenderer.tsx
/**
 * CachedCodeRenderer - 使用 shiki-stream 实现流式代码高亮
 *
 * 基于 shiki-stream 的实现，参考 Vue 版本 CachedCodeRenderer.vue
 * 
 * 与 Vue 版本保持一致：
 * - 在组件初始化时创建 stream（不在 useEffect 中）
 * - 直接消费 stream，不使用单独的 Renderer 组件
 * - hasStreamError 状态和错误处理
 * - class: 'shiki incremark-code-stream'
 */
import type { ThemedToken } from '@shikijs/core'
import { objectId } from '@antfu/utils'
import { getTokenStyleObject } from '@shikijs/core'
import React, { useEffect, useRef, useState, forwardRef, useImperativeHandle } from 'react'
import { CodeToTokenTransformStream } from 'shiki-stream'

export interface CachedCodeRendererProps {
  code: string
  lang: string
  theme: string
  highlighter: any
  onStreamStart?: () => void
  onStreamEnd?: () => void
  onStreamError?: () => void
}

export interface CachedCodeRendererRef {
  reset: () => void
}

/**
 * CachedCodeRenderer - 参考 Vue 版本实现
 *
 * 期望 code prop 只会增量更新，不会被设置为新值。
 * 如果需要设置新值，请在发生时设置不同的 key prop。
 */
export const CachedCodeRenderer = forwardRef<CachedCodeRendererRef, CachedCodeRendererProps>(
  function CachedCodeRenderer({ code, lang, theme, highlighter, onStreamStart, onStreamEnd, onStreamError }, ref) {
    const [hasStreamError, setHasStreamError] = useState(false)
    const [tokens, setTokens] = useState<ThemedToken[]>([])
    
    // 使用 ref 存储 stream 相关状态（与 Vue 版本的模块级变量对应）
    const streamRef = useRef<{
      controller: ReadableStreamController<string> | null
      index: number
      initialized: boolean
      streamConsumed: boolean
    }>({
      controller: null,
      index: 0,
      initialized: false,
      streamConsumed: false
    })

    // 暴露 ref 方法
    useImperativeHandle(ref, () => ({
      reset: () => {
        setHasStreamError(false)
        setTokens([])
        streamRef.current.index = 0
      }
    }))

    // 初始化并消费 stream（只执行一次，与 Vue 版本的 setup 对齐）
    useEffect(() => {
      // 防止 React 严格模式下重复执行
      if (streamRef.current.initialized) return
      streamRef.current.initialized = true

      // 创建文本流（与 Vue 版本对齐）
      const textStream = new ReadableStream<string>({
        start(controller) {
          streamRef.current.controller = controller
        },
      })

      let tokenStream: ReadableStream<any> | null = null

      try {
        tokenStream = textStream.pipeThrough(
          new CodeToTokenTransformStream({
            highlighter,
            lang,
            theme,
            allowRecalls: true,
          })
        )
      } catch (error) {
        console.error('Failed to create token stream:', error)
        setHasStreamError(true)
        onStreamError?.()
        return
      }

      // 直接消费 stream（与 Vue 版本对齐，不使用单独的 Renderer）
      let started = false
      let tokenCount = 0

      tokenStream.pipeTo(new WritableStream({
        write(token) {
          if (!started) {
            started = true
            onStreamStart?.()
          }
          if ('recall' in token) {
            setTokens(prev => {
              const newTokens = [...prev]
              newTokens.splice(newTokens.length - token.recall, token.recall)
              return newTokens
            })
          } else {
            setTokens(prev => [...prev, token])
          }
          tokenCount++
        },
        close: () => {
          console.log(`[React CodeRenderer] Stream completed, total tokens: ${tokenCount}`)
          onStreamEnd?.()
        },
      })).catch((error) => {
        console.error('Stream error:', error)
        setHasStreamError(true)
        onStreamError?.()
      })

      streamRef.current.streamConsumed = true
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []) // 空依赖，只执行一次

    // 监听 code 变化，增量推送到流中（与 Vue 版本的 watch 对齐）
    useEffect(() => {
      const { controller, index } = streamRef.current
      if (!controller || hasStreamError) return

      if (code.length > index) {
        const incremental = code.slice(index)
        try {
          controller.enqueue(incremental as any)
          streamRef.current.index = code.length
        } catch {
          // Stream 已关闭，忽略错误
        }
      }
    }, [code, hasStreamError])

    // 渲染（与 Vue 版本对齐）
    // SSR 或错误时渲染原始代码
    if (hasStreamError || tokens.length === 0) {
      return (
        <pre className="shiki incremark-code-stream">
          <code>{code}</code>
        </pre>
      )
    }

    return (
      <pre className="shiki incremark-code-stream">
        <code>
          {tokens.map((token) => {
            // 获取样式
            const styleObj: unknown = token.htmlStyle || getTokenStyleObject(token)
            // React 需要 camelCase 样式属性
            const reactStyle: React.CSSProperties = {}
            if (typeof styleObj === 'string') {
              // 解析字符串样式
              styleObj.split(';').forEach((rule: string) => {
                const colonIndex = rule.indexOf(':')
                if (colonIndex > 0) {
                  const key = rule.slice(0, colonIndex).trim()
                  const value = rule.slice(colonIndex + 1).trim()
                  if (key && value) {
                    const camelKey = key.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
                    ;(reactStyle as any)[camelKey] = value
                  }
                }
              })
            } else if (styleObj && typeof styleObj === 'object') {
              for (const [key, value] of Object.entries(styleObj as Record<string, unknown>)) {
                const camelKey = key.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
                ;(reactStyle as any)[camelKey] = value
              }
            }

            return (
              <span key={objectId(token)} style={reactStyle}>
                {token.content}
              </span>
            )
          })}
        </code>
      </pre>
    )
  }
)
