// packages/svelte/src/components/ConfigProvider.svelte
<script lang="ts">
  import type { IncremarkLocale } from '@incremark/shared'
  import { zhCN } from '@incremark/shared'
  import { provideLocale } from '../stores/useLocale.svelte'

  interface Props {
    locale?: IncremarkLocale
    children: import('svelte').Snippet
  }

  // 提供 locale 给子组件（确保不是 undefined）
  const { locale, children }: Props = $props()

  // 在组件初始化时同步设置 context
  // 使用函数返回 locale 以支持响应式更新
  provideLocale(() => locale || zhCN)
</script>

{@render children()}

// packages/react/src/components/ConfigProvider.tsx
import { createContext, useMemo, type ReactNode } from 'react'
import type { IncremarkLocale } from '@incremark/shared'
import { zhCN } from '@incremark/shared'

interface LocaleContextType {
  locale: IncremarkLocale
}

export const LocaleContext = createContext<LocaleContextType | null>(null)

interface ConfigProviderProps {
  children: ReactNode
  locale?: IncremarkLocale
}

// 提供 locale 给子组件（确保不是 undefined）
export function ConfigProvider({ children, locale }: ConfigProviderProps) {
  const contextValue = useMemo(() => ({ locale: locale || zhCN }), [locale])

  return <LocaleContext.Provider value={contextValue}>{children}</LocaleContext.Provider>
}
