// packages/solid/src/components/IncremarkParagraph.tsx
/* @jsxImportSource solid-js */

import type { Paragraph } from 'mdast'
import { Component } from 'solid-js'
import { IncremarkInline } from './IncremarkInline'

export interface IncremarkParagraphProps {
  node: Paragraph
}

export const IncremarkParagraph: Component<IncremarkParagraphProps> = (props) => {
  return (
    <p class="incremark-paragraph">
      <IncremarkInline nodes={props.node.children} />
    </p>
  )
}

// packages/react/src/components/IncremarkParagraph.tsx
import React from 'react'
import type { Paragraph, PhrasingContent } from 'mdast'
import { IncremarkInline } from './IncremarkInline'

export interface IncremarkParagraphProps {
  node: Paragraph
}

/**
 * Paragraph 组件
 * 
 * 渲染 Markdown 段落
 */
export const IncremarkParagraph: React.FC<IncremarkParagraphProps> = ({ node }) => {
  return (
    <p className="incremark-paragraph">
      <IncremarkInline nodes={node.children as PhrasingContent[]} />
    </p>
  )
}
