// packages/vue/src/components/IncremarkBlockquote.vue
<script setup lang="ts">
import type { Blockquote } from 'mdast'
import IncremarkParagraph from './IncremarkParagraph.vue'

defineProps<{
  node: Blockquote
}>()
</script>

<template>
  <blockquote class="incremark-blockquote">
    <template v-for="(child, index) in node.children" :key="index">
      <IncremarkParagraph v-if="child.type === 'paragraph'" :node="child" />
      <div v-else class="unknown-child">{{ child.type }}</div>
    </template>
  </blockquote>
</template>

// packages/react/src/components/IncremarkBlockquote.tsx
import React from 'react'
import type { Blockquote } from 'mdast'
import { IncremarkParagraph } from './IncremarkParagraph'

export interface IncremarkBlockquoteProps {
  node: Blockquote
}

export const IncremarkBlockquote: React.FC<IncremarkBlockquoteProps> = ({ node }) => {
  return (
    <blockquote className="incremark-blockquote">
      {node.children.map((child, index) => {
        if (child.type === 'paragraph') {
          return <IncremarkParagraph key={index} node={child} />
        }
        return <div key={index} className="unknown-child">{child.type}</div>
      })}
    </blockquote>
  )
}
