// packages/svelte/src/components/IncremarkContent.svelte
<!--
  @file IncremarkContent.svelte - 开箱即用的 Markdown 渲染组件
  @description 自动处理流式内容和普通内容的高级组件
-->

<script lang="ts">
  import { useIncremark, type UseIncremarkOptions } from '../stores/useIncremark'
  import type { IncremarkContentProps } from './types'
  import Incremark from './Incremark.svelte'
  import { get } from 'svelte/store'

  let {
    stream,
    content,
    components = {},
    customContainers = {},
    customCodeBlocks = {},
    codeBlockConfigs = {},
    isFinished = false,
    incremarkOptions,
    pendingClass = 'incremark-pending',
    showBlockStatus = false
  }: IncremarkContentProps = $props()

  // 合并默认选项（初始化时使用）
  const initialOptions: UseIncremarkOptions = {
    gfm: true,
    htmlTree: true,
    containers: true,
    math: true,
    ...incremarkOptions
  }

  const { blocks, append, finalize, render, reset, isDisplayComplete, markdown, typewriter } = useIncremark(initialOptions)

  // 监听 incremarkOptions 的变化，更新 typewriter 配置
  $effect(() => {
    if (incremarkOptions?.typewriter) {
      typewriter.setOptions(incremarkOptions.typewriter)
    }
  })

  // 派生状态
  const isStreamMode = $derived(typeof stream === 'function')

  // 保存前一个 content 值用于增量更新
  let prevContent: string | undefined = $state(undefined)
  let isStreaming = $state(false)

  async function handleStreamInput() {
    if (!stream || isStreaming) return

    isStreaming = true
    try {
      const streamGen = stream()

      for await (const chunk of streamGen) {
        append(chunk)
      }

      finalize()
    } catch (error) {
      console.error('Stream error: ', error)
      finalize()
    } finally {
      isStreaming = false
    }
  }

  function handleContentInput(newContent?: string, oldContent?: string) {
    if (!newContent) {
      if (oldContent) {
        reset()
      }
      return
    }

    if (newContent?.startsWith(oldContent ?? '')) {
      const delta = newContent.slice((oldContent || '').length)
      append(delta)
    } else {
      render(newContent)
    }
  }

  // 监听 content 变化
  $effect(() => {
    if (isStreamMode) {
      handleStreamInput()
    } else {
      handleContentInput(content, prevContent)
    }
    prevContent = content
  })

  // 监听 isFinished 变化
  $effect(() => {
    if (isFinished && content === get(markdown)) {
      finalize()
    }
  })
</script>

<Incremark
  blocks={$blocks}
  isDisplayComplete={$isDisplayComplete}
  {pendingClass}
  {showBlockStatus}
  {components}
  {customContainers}
  {customCodeBlocks}
  {codeBlockConfigs}
/>

// packages/react/src/components/IncremarkContent.tsx
import React, { useEffect, useRef, useMemo, useCallback } from 'react'
import { useIncremark } from '../hooks/useIncremark'
import type { IncremarkContentProps } from '../types'
import { Incremark } from './Incremark'
import { IncremarkContainerProvider } from './IncremarkContainerProvider'

/**
 * IncremarkContent 组件
 *
 * 提供开箱即用的 Markdown 渲染体验，自动处理流式内容和普通内容
 *
 * @example
 * ```tsx
 * // 普通内容
 * <IncremarkContent content={markdownString} />
 *
 * // 流式内容
 * <IncremarkContent stream={() => streamGenerator()} />
 *
 * // 增量更新内容
 * <IncremarkContent content={partialContent} isFinished={false} />
 * ```
 */
export const IncremarkContent: React.FC<IncremarkContentProps> = (props) => {
  const {
    stream,
    content,
    components,
    customContainers,
    customCodeBlocks,
    codeBlockConfigs,
    isFinished = false,
    incremarkOptions,
    showBlockStatus,
    pendingClass
  } = props

  // 初始化时使用的选项（使用 ref 避免重建 hook）
  const initialOptionsRef = useRef({
    gfm: true,
    htmlTree: true,
    containers: true,
    math: true,
    ...incremarkOptions
  })

  const { blocks, append, finalize, render, reset, isDisplayComplete, markdown, typewriter, _definitionsContextValue } = useIncremark(initialOptionsRef.current)

  // 监听 incremarkOptions 的变化，更新 typewriter 配置
  useEffect(() => {
    if (incremarkOptions?.typewriter) {
      typewriter.setOptions(incremarkOptions.typewriter)
    }
  }, [incremarkOptions?.typewriter, typewriter])

  const isStreamMode = useMemo(() => typeof stream === 'function', [stream])
  const prevContentRef = useRef<string | undefined>(undefined)
  const isStreamingRef = useRef(false)

  const handleStreamInput = useCallback(async () => {
    if (!stream || isStreamingRef.current) return

    isStreamingRef.current = true
    try {
      const streamGen = stream()

      for await (const chunk of streamGen) {
        append(chunk)
      }

      finalize()
    } catch (error) {
      console.error('Stream error: ', error)
      finalize()
    } finally {
      isStreamingRef.current = false
    }
  }, [stream, append, finalize])

  const handleContentInput = useCallback((newContent?: string, oldContent?: string) => {
    if (!newContent) {
      if (oldContent) {
        reset()
      }
      return
    }

    if (newContent?.startsWith(oldContent ?? '')) {
      const delta = newContent.slice((oldContent || '').length)
      append(delta)
    } else {
      render(newContent)
    }
  }, [append, render, reset])

  // 监听 content 变化
  useEffect(() => {
    if (isStreamMode) {
      handleStreamInput()
    } else {
      handleContentInput(content, prevContentRef.current)
    }
    prevContentRef.current = content
  }, [content, isStreamMode, handleStreamInput, handleContentInput])

  // 监听 isFinished 变化
  useEffect(() => {
    if (isFinished && content === markdown) {
      finalize()
    }
  }, [isFinished, content, markdown, finalize])

  return (
    <IncremarkContainerProvider definitions={_definitionsContextValue}>
      <Incremark
        blocks={blocks}
        isDisplayComplete={isDisplayComplete}
        showBlockStatus={showBlockStatus}
        pendingClass={pendingClass}
        components={components}
        customContainers={customContainers}
        customCodeBlocks={customCodeBlocks}
        codeBlockConfigs={codeBlockConfigs}
      />
    </IncremarkContainerProvider>
  )
}
