// packages/solid/src/components/IncremarkDefault.tsx
/* @jsxImportSource solid-js */

import type { RootContent } from 'mdast'
import { Component } from 'solid-js'

export interface IncremarkDefaultProps {
  node: RootContent
}

/**
 * 默认渲染组件
 * 用于未知类型的节点，显示调试信息
 */
export const IncremarkDefault: Component<IncremarkDefaultProps> = (props) => {
  return (
    <pre class="incremark-debug">
      <code>{JSON.stringify(props.node, null, 2)}</code>
    </pre>
  )
}

// packages/react/src/components/IncremarkDefault.tsx
import React from 'react'
import type { RootContent } from 'mdast'

export interface IncremarkDefaultProps {
  node: RootContent
}

export const IncremarkDefault: React.FC<IncremarkDefaultProps> = ({ node }) => {
  return (
    <div className="incremark-default">
      <span className="type-badge">{node.type}</span>
      <pre>{JSON.stringify(node, null, 2)}</pre>
    </div>
  )
}
