// packages/vue/src/components/IncremarkCodeMermaid.vue
<script setup lang="ts">
import type { Code } from 'mdast'
import { computed, ref, onUnmounted, shallowRef, watch } from 'vue'
import { GravityMermaid, LucideCode, LucideEye, LucideCopy, LucideCopyCheck } from '@incremark/icons'
import { isClipboardAvailable } from '@incremark/shared'
import SvgIcon from './SvgIcon.vue'
import { useLocale } from '../composables/useLocale'

interface Props {
  node: Code
  /** Mermaid 渲染延迟（毫秒），用于流式输入时防抖 */
  mermaidDelay?: number
}

const props = withDefaults(defineProps<Props>(), {
  mermaidDelay: 500
})

// 使用 i18n
const { t } = useLocale()

const mermaidSvg = ref('')
const mermaidError = ref('')
const mermaidLoading = ref(false)
const mermaidRef = shallowRef<any>(null)
let mermaidTimer: ReturnType<typeof setTimeout> | null = null
// 视图模式：'preview' | 'source'
const mermaidViewMode = ref<'preview' | 'source'>('preview')

function toggleMermaidView() {
  mermaidViewMode.value = mermaidViewMode.value === 'preview' ? 'source' : 'preview'
}

const code = computed(() => props.node.value)

// Mermaid 渲染（带防抖动）
function scheduleRenderMermaid() {
  if (!code.value) return

  // 清除之前的定时器
  if (mermaidTimer) {
    clearTimeout(mermaidTimer)
  }

  // 显示加载状态
  mermaidLoading.value = true

  // 防抖动延迟渲染
  mermaidTimer = setTimeout(() => {
    doRenderMermaid()
  }, props.mermaidDelay)
}

async function doRenderMermaid() {
  if (!code.value) return

  mermaidError.value = ''

  try {
    // 动态导入 mermaid
    if (!mermaidRef.value) {
      // @ts-ignore - mermaid 是可选依赖
      const mermaidModule = await import('mermaid')
      mermaidRef.value = mermaidModule.default
      mermaidRef.value.initialize({
        startOnLoad: false,
        theme: 'dark',
        securityLevel: 'loose',
        suppressErrorRendering: true
      })
    }

    const mermaid = mermaidRef.value
    const id = `mermaid-${Date.now()}-${Math.random().toString(36).slice(2)}`

    const { svg } = await mermaid.render(id, code.value)
    mermaidSvg.value = svg
  } catch (e: any) {
    // 不显示错误，可能是代码还不完整
    mermaidError.value = ''
    mermaidSvg.value = ''
  } finally {
    mermaidLoading.value = false
  }
}

// 监听代码变化，重新渲染
watch(code, scheduleRenderMermaid, { immediate: true })

// 组件卸载时清理定时器
onUnmounted(() => {
  if (mermaidTimer) {
    clearTimeout(mermaidTimer)
  }
  if (copyTimeoutId) {
    clearTimeout(copyTimeoutId)
  }
})

const copied = ref(false)
let copyTimeoutId: ReturnType<typeof setTimeout> | null = null

async function copyCode() {
  if (!isClipboardAvailable()) return

  try {
    await navigator.clipboard.writeText(code.value)
    copied.value = true

    // 清理之前的定时器
    if (copyTimeoutId) {
      clearTimeout(copyTimeoutId)
    }

    copyTimeoutId = setTimeout(() => {
      copied.value = false
    }, 2000)
  } catch {
    // 复制失败静默处理
  }
}
</script>

<template>
  <div class="incremark-mermaid">
    <div class="mermaid-header">
      <span class="language">
        <SvgIcon :svg="GravityMermaid" class="language-icon" />
        MERMAID
      </span>
      <div class="mermaid-actions">
        <button
          class="code-btn"
          @click="toggleMermaidView"
          type="button"
          :disabled="!mermaidSvg"
          :aria-label="mermaidViewMode === 'preview' ? t('mermaid.viewSource') : t('mermaid.preview')"
          :title="mermaidViewMode === 'preview' ? 'View Source' : 'Preview'"
        >
          <SvgIcon :svg="mermaidViewMode === 'preview' ? LucideCode : LucideEye" />
        </button>
        <button
          class="code-btn"
          @click="copyCode"
          type="button"
          :aria-label="copied ? t('mermaid.copied') : t('mermaid.copy')"
          :title="copied ? 'Copied!' : 'Copy'"
        >
          <SvgIcon :svg="copied ? LucideCopyCheck : LucideCopy" />
        </button>
      </div>
    </div>
    <div class="mermaid-content">
      <!-- 加载中 -->
      <div v-if="mermaidLoading && !mermaidSvg" class="mermaid-loading">
        <pre class="mermaid-source-code">{{ code }}</pre>
      </div>
      <!-- 源码模式 -->
      <pre v-else-if="mermaidViewMode === 'source'" class="mermaid-source-code">{{ code }}</pre>
      <!-- 预览模式 -->
      <div v-else-if="mermaidSvg" v-html="mermaidSvg" class="mermaid-svg" />
      <!-- 无法渲染时显示源码 -->
      <pre v-else class="mermaid-source-code">{{ code }}</pre>
    </div>
  </div>
</template>

// packages/react/src/components/IncremarkCodeMermaid.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react'
import type { Code } from 'mdast'
import { GravityMermaid, LucideCode, LucideEye, LucideCopy, LucideCopyCheck } from '@incremark/icons'
import { isClipboardAvailable } from '@incremark/shared'
import { SvgIcon } from './SvgIcon'
import { useLocale } from '../hooks/useLocale'

export interface IncremarkCodeMermaidProps {
  node: Code
  /** Mermaid 渲染延迟（毫秒），用于流式输入时防抖 */
  mermaidDelay?: number
}

export const IncremarkCodeMermaid: React.FC<IncremarkCodeMermaidProps> = ({
  node,
  mermaidDelay = 500
}) => {
  const [copied, setCopied] = useState(false)

  // 使用 i18n
  const { t } = useLocale()

  const [mermaidSvg, setMermaidSvg] = useState('')
  const [mermaidLoading, setMermaidLoading] = useState(false)
  const [mermaidViewMode, setMermaidViewMode] = useState<'preview' | 'source'>('preview')

  const mermaidRef = useRef<any>(null)
  const mermaidTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const copyTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const code = node.value

  const toggleMermaidView = useCallback(() => {
    setMermaidViewMode(prev => prev === 'preview' ? 'source' : 'preview')
  }, [])

  const copyCode = useCallback(async () => {
    if (!isClipboardAvailable()) return

    try {
      await navigator.clipboard.writeText(code)
      setCopied(true)

      if (copyTimeoutRef.current) {
        clearTimeout(copyTimeoutRef.current)
      }
      copyTimeoutRef.current = setTimeout(() => setCopied(false), 2000)
    } catch {
      // 复制失败静默处理
    }
  }, [code])

  const doRenderMermaid = useCallback(async () => {
    if (!code) return

    try {
      if (!mermaidRef.current) {
        const mermaidModule = await import('mermaid')
        mermaidRef.current = mermaidModule.default
        mermaidRef.current.initialize({
          startOnLoad: false,
          theme: 'dark',
          securityLevel: 'loose',
          suppressErrorRendering: true
        })
      }

      const mermaid = mermaidRef.current
      const id = `mermaid-${Date.now()}-${Math.random().toString(36).slice(2)}`
      const { svg } = await mermaid.render(id, code)
      setMermaidSvg(svg)
    } catch {
      setMermaidSvg('')
    } finally {
      setMermaidLoading(false)
    }
  }, [code])

  const scheduleRenderMermaid = useCallback(() => {
    if (!code) return

    if (mermaidTimerRef.current) {
      clearTimeout(mermaidTimerRef.current)
    }

    setMermaidLoading(true)
    mermaidTimerRef.current = setTimeout(() => {
      doRenderMermaid()
    }, mermaidDelay)
  }, [code, mermaidDelay, doRenderMermaid])

  useEffect(() => {
    scheduleRenderMermaid()
  }, [scheduleRenderMermaid])

  useEffect(() => {
    return () => {
      if (mermaidTimerRef.current) {
        clearTimeout(mermaidTimerRef.current)
      }
      if (copyTimeoutRef.current) {
        clearTimeout(copyTimeoutRef.current)
      }
    }
  }, [])

  return (
    <div className="incremark-mermaid">
      <div className="mermaid-header">
        <span className="language">
          <SvgIcon svg={GravityMermaid} className="language-icon" />
          MERMAID
        </span>
        <div className="mermaid-actions">
          <button
            className="code-btn"
            onClick={toggleMermaidView}
            type="button"
            disabled={!mermaidSvg}
            aria-label={mermaidViewMode === 'preview' ? t('mermaid.viewSource') : t('mermaid.preview')}
            title={mermaidViewMode === 'preview' ? 'View Source' : 'Preview'}
          >
            <SvgIcon svg={mermaidViewMode === 'preview' ? LucideCode : LucideEye} />
          </button>
          <button
            className="code-btn"
            onClick={copyCode}
            type="button"
            aria-label={copied ? t('mermaid.copied') : t('mermaid.copy')}
            title={copied ? 'Copied!' : 'Copy'}
          >
            <SvgIcon svg={copied ? LucideCopyCheck : LucideCopy} />
          </button>
        </div>
      </div>
      <div className="mermaid-content">
        {mermaidLoading && !mermaidSvg ? (
          <div className="mermaid-loading">
            <pre className="mermaid-source-code">{code}</pre>
          </div>
        ) : mermaidViewMode === 'source' ? (
          <pre className="mermaid-source-code">{code}</pre>
        ) : mermaidSvg ? (
          <div className="mermaid-svg" dangerouslySetInnerHTML={{ __html: mermaidSvg }} />
        ) : (
          <pre className="mermaid-source-code">{code}</pre>
        )}
      </div>
    </div>
  )
}
