// packages/react/src/components/AutoScrollContainer.tsx
import React, {
  useRef,
  useEffect,
  useCallback,
  useState,
  forwardRef,
  useImperativeHandle
} from 'react'

export interface AutoScrollContainerProps {
  /** 子元素 */
  children: React.ReactNode
  /** 是否启用自动滚动 */
  enabled?: boolean
  /** 触发自动滚动的底部阈值（像素） */
  threshold?: number
  /** 滚动行为 */
  behavior?: ScrollBehavior
  /** 容器样式 */
  style?: React.CSSProperties
  /** 容器类名 */
  className?: string
}

export interface AutoScrollContainerRef {
  /** 强制滚动到底部 */
  scrollToBottom: () => void
  /** 是否用户手动向上滚动了 */
  isUserScrolledUp: () => boolean
  /** 容器元素引用 */
  container: HTMLDivElement | null
}

/**
 * 自动滚动容器
 *
 * 当内容更新时自动滚动到底部。
 * 如果用户手动向上滚动，则暂停自动滚动，直到用户再次滚动到底部。
 *
 * @example
 * ```tsx
 * const scrollRef = useRef<AutoScrollContainerRef>(null)
 *
 * <AutoScrollContainer ref={scrollRef} enabled={true}>
 *   <Incremark blocks={blocks} />
 * </AutoScrollContainer>
 *
 * // 强制滚动到底部
 * scrollRef.current?.scrollToBottom()
 * ```
 */
export const AutoScrollContainer = forwardRef<AutoScrollContainerRef, AutoScrollContainerProps>(
  (
    {
      children,
      enabled = true,
      threshold = 50,
      behavior = 'instant',
      style,
      className
    },
    ref
  ) => {
    const containerRef = useRef<HTMLDivElement>(null)
    const [isUserScrolledUp, setIsUserScrolledUp] = useState(false)
    
    // 记录上一次滚动位置，用于判断滚动方向
    const lastScrollTopRef = useRef(0)
    const lastScrollHeightRef = useRef(0)

    /**
     * 检查是否在底部附近
     */
    const isNearBottom = useCallback((): boolean => {
      const container = containerRef.current
      if (!container) return true

      const { scrollTop, scrollHeight, clientHeight } = container
      return scrollHeight - scrollTop - clientHeight <= threshold
    }, [threshold])

    /**
     * 滚动到底部
     */
    const scrollToBottom = useCallback(
      (force = false): void => {
        const container = containerRef.current
        if (!container) return

        // 如果用户手动向上滚动了，且不是强制滚动，则不自动滚动
        if (isUserScrolledUp && !force) return

        container.scrollTo({
          top: container.scrollHeight,
          behavior
        })
      },
      [isUserScrolledUp, behavior]
    )

    /**
     * 检查是否有滚动条
     */
    const hasScrollbar = useCallback((): boolean => {
      const container = containerRef.current
      if (!container) return false
      return container.scrollHeight > container.clientHeight
    }, [])

    /**
     * 处理滚动事件
     */
    const handleScroll = useCallback((): void => {
      const container = containerRef.current
      if (!container) return

      const { scrollTop, scrollHeight, clientHeight } = container
      
      // 如果没有滚动条，恢复自动滚动
      if (scrollHeight <= clientHeight) {
        setIsUserScrolledUp(false)
        lastScrollTopRef.current = 0
        lastScrollHeightRef.current = scrollHeight
        return
      }
      
      // 检查用户是否滚动到底部附近
      if (isNearBottom()) {
        // 用户滚动到底部，恢复自动滚动
        setIsUserScrolledUp(false)
      } else {
        // 判断是否是用户主动向上滚动
        // 条件：scrollTop 减少（向上滚动）且 scrollHeight 没有变化（不是因为内容增加）
        const isScrollingUp = scrollTop < lastScrollTopRef.current
        const isContentUnchanged = scrollHeight === lastScrollHeightRef.current
        
        if (isScrollingUp && isContentUnchanged) {
          // 用户主动向上滚动，暂停自动滚动
          setIsUserScrolledUp(true)
        }
      }
      
      // 更新记录
      lastScrollTopRef.current = scrollTop
      lastScrollHeightRef.current = scrollHeight
    }, [isNearBottom])

    // 初始化滚动位置记录
    useEffect(() => {
      const container = containerRef.current
      if (container) {
        lastScrollTopRef.current = container.scrollTop
        lastScrollHeightRef.current = container.scrollHeight
      }
    }, [])

    // 监听内容变化
    useEffect(() => {
      const container = containerRef.current
      if (!container || !enabled) return

      const observer = new MutationObserver(() => {
        // 使用 requestAnimationFrame 确保 DOM 更新完成
        requestAnimationFrame(() => {
          if (!containerRef.current) return
          
          const { scrollHeight, clientHeight } = containerRef.current
          
          // 如果没有滚动条，重置状态
          if (scrollHeight <= clientHeight) {
            setIsUserScrolledUp(false)
          }
          
          // 更新 scrollHeight 记录（内容变化后）
          lastScrollHeightRef.current = scrollHeight
          
          // 自动滚动
          if (!isUserScrolledUp) {
            scrollToBottom()
          }
        })
      })

      observer.observe(container, {
        childList: true,
        subtree: true,
        characterData: true
      })

      return () => observer.disconnect()
    }, [enabled, isUserScrolledUp, scrollToBottom])

    // 暴露方法给父组件
    useImperativeHandle(
      ref,
      () => ({
        scrollToBottom: () => scrollToBottom(true),
        isUserScrolledUp: () => isUserScrolledUp,
        container: containerRef.current
      }),
      [scrollToBottom, isUserScrolledUp]
    )

    return (
      <div
        ref={containerRef}
        className={`auto-scroll-container ${className || ''}`.trim()}
        style={style}
        onScroll={handleScroll}
      >
        {children}
      </div>
    )
  }
)

AutoScrollContainer.displayName = 'AutoScrollContainer'

// packages/solid/src/components/AutoScrollContainer.tsx
/* @jsxImportSource solid-js */

import { Component, createEffect, createSignal, onCleanup, onMount, JSX } from 'solid-js'
import type { Accessor } from 'solid-js'

export interface AutoScrollContainerProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** 是否启用自动滚动 */
  enabled?: Accessor<boolean> | boolean
  /** 触发自动滚动的底部阈值（像素） */
  threshold?: number
  /** 滚动行为 */
  behavior?: ScrollBehavior
}

/**
 * 自动滚动容器组件
 *
 * 当内容更新时自动滚动到底部，除非用户手动向上滚动
 */
export const AutoScrollContainer: Component<AutoScrollContainerProps> = (props) => {
  let containerRef: HTMLDivElement | undefined

  const [isUserScrolledUp, setIsUserScrolledUp] = createSignal(false)

  // 记录上一次滚动位置，用于判断滚动方向
  let lastScrollTop = 0
  let lastScrollHeight = 0

  const enabled = () => typeof props.enabled === 'function' ? props.enabled() : props.enabled ?? true
  const threshold = () => props.threshold ?? 50
  const scrollBehavior = () => props.behavior ?? 'instant'

  /**
   * 检查是否在底部附近
   */
  function isNearBottom(): boolean {
    if (!containerRef) return true

    const { scrollTop, scrollHeight, clientHeight } = containerRef
    return scrollHeight - scrollTop - clientHeight <= threshold()
  }

  /**
   * 滚动到底部
   */
  function scrollToBottom(force = false): void {
    if (!containerRef) return

    // 如果用户手动向上滚动了，且不是强制滚动，则不自动滚动
    if (isUserScrolledUp() && !force) return

    containerRef.scrollTo({
      top: containerRef.scrollHeight,
      behavior: scrollBehavior()
    })
  }

  /**
   * 检查是否有滚动条
   */
  function hasScrollbar(): boolean {
    if (!containerRef) return false
    return containerRef.scrollHeight > containerRef.clientHeight
  }

  /**
   * 处理滚动事件
   */
  function handleScroll(): void {
    if (!containerRef) return

    const { scrollTop, scrollHeight, clientHeight } = containerRef

    // 如果没有滚动条，恢复自动滚动
    if (scrollHeight <= clientHeight) {
      setIsUserScrolledUp(false)
      lastScrollTop = 0
      lastScrollHeight = scrollHeight
      return
    }

    // 检查用户是否滚动到底部附近
    if (isNearBottom()) {
      // 用户滚动到底部，恢复自动滚动
      setIsUserScrolledUp(false)
    } else {
      // 判断是否是用户主动向上滚动
      // 条件：scrollTop 减少（向上滚动）且 scrollHeight 没有变化（不是因为内容增加）
      const isScrollingUp = scrollTop < lastScrollTop
      const isContentUnchanged = scrollHeight === lastScrollHeight

      if (isScrollingUp && isContentUnchanged) {
        // 用户主动向上滚动，暂停自动滚动
        setIsUserScrolledUp(true)
      }
    }

    // 更新记录
    lastScrollTop = scrollTop
    lastScrollHeight = scrollHeight
  }

  // 监听内容变化（使用 MutationObserver）
  let observer: MutationObserver | null = null

  onMount(() => {
    if (!containerRef) return

    // 初始化滚动位置记录
    lastScrollTop = containerRef.scrollTop
    lastScrollHeight = containerRef.scrollHeight

    observer = new MutationObserver(() => {
      // 使用 requestAnimationFrame 避免 layout thrashing
      requestAnimationFrame(() => {
        if (!containerRef) return

        // 如果没有滚动条，重置状态
        if (!hasScrollbar()) {
          setIsUserScrolledUp(false)
        }

        // 更新 scrollHeight 记录（内容变化后）
        lastScrollHeight = containerRef.scrollHeight

        // 自动滚动
        if (enabled() && !isUserScrolledUp()) {
          scrollToBottom()
        }
      })
    })

    observer.observe(containerRef, {
      childList: true,
      subtree: true,
      characterData: true
    })
  })

  onCleanup(() => {
    observer?.disconnect()
  })

  return (
    <div
      ref={containerRef}
      class="auto-scroll-container"
      onScroll={handleScroll}
    >
      {props.children}
    </div>
  )
}
