// packages/vue/src/components/IncremarkParagraph.vue
<script setup lang="ts">
import type { Paragraph } from 'mdast'
import IncremarkInline from './IncremarkInline.vue'

defineProps<{
  node: Paragraph
}>()
</script>

<template>
  <p class="incremark-paragraph">
    <IncremarkInline :nodes="node.children" />
  </p>
</template>

<style scoped>
.incremark-paragraph {
  margin: 0.75em 0;
  line-height: 1.6;
}
</style>

// packages/solid/src/components/IncremarkParagraph.tsx
/* @jsxImportSource solid-js */

import type { Paragraph } from 'mdast'
import { Component } from 'solid-js'
import { IncremarkInline } from './IncremarkInline'

export interface IncremarkParagraphProps {
  node: Paragraph
}

export const IncremarkParagraph: Component<IncremarkParagraphProps> = (props) => {
  return (
    <p class="incremark-paragraph">
      <IncremarkInline nodes={props.node.children} />
    </p>
  )
}
