// packages/svelte/src/components/IncremarkFootnotes.svelte
<!--
  @file IncremarkFootnotes.svelte - 脚注列表组件
  @description 在文档底部渲染所有脚注定义，按引用出现的顺序排列
-->

<script lang="ts">
  import type { Readable } from 'svelte/store'
  import type { FootnoteDefinition, RootContent } from 'mdast'
  import { getDefinitionsContext } from '../context/definitionsContext'
  import IncremarkRenderer from './IncremarkRenderer.svelte'


  const context = getDefinitionsContext()
  const footnoteDefinitions = $derived(context?.footnoteDefinitions ?? {});
  const footnoteReferenceOrder = $derived(context?.footnoteReferenceOrder ?? []);

  /**
   * 按引用顺序排列的脚注列表
   * 只显示已有定义的脚注
   */
  const orderedFootnotes = $derived.by(() => {
    if (!footnoteReferenceOrder || !footnoteDefinitions) {
      return []
    }
    const order = $footnoteReferenceOrder
    const definitions = $footnoteDefinitions
    return order
      .map(identifier => ({
        identifier,
        definition: definitions[identifier]
      }))
      .filter(item => item.definition !== undefined)
  })

  /**
   * 是否有脚注需要显示
   */
  const hasFootnotes = $derived(orderedFootnotes.length > 0)
</script>

{#if hasFootnotes}
  <section class="incremark-footnotes">
    <hr class="incremark-footnotes-divider" />
    <ol class="incremark-footnotes-list">
      {#each orderedFootnotes as item, index (item.identifier)}
        <li
          id="fn-{item.identifier}"
          class="incremark-footnote-item"
        >
          <div class="incremark-footnote-content">
            <!-- 脚注序号 -->
            <span class="incremark-footnote-number">{index + 1}.</span>
            
            <!-- 脚注内容 -->
            <div class="incremark-footnote-body">
              {#each item.definition.children as child, childIndex (childIndex)}
                <IncremarkRenderer node={child as RootContent} />
              {/each}
            </div>
          </div>
          
          <!-- 返回链接 -->
          <a 
            href="#fnref-{item.identifier}" 
            class="incremark-footnote-backref"
            aria-label="返回引用位置"
          >
            ↩
          </a>
        </li>
      {/each}
    </ol>
  </section>
{/if}

// packages/solid/src/components/IncremarkFootnotes.tsx
/* @jsxImportSource solid-js */

import type { FootnoteDefinition, RootContent } from 'mdast'
import { Component, For, Show } from 'solid-js'
import { useDefinationsContext } from '../composables/useDefinationsContext'
import IncremarkRenderer from './IncremarkRenderer'

export interface IncremarkFootnotesProps {}

/**
 * 脚注列表组件
 *
 * 在文档底部渲染所有脚注定义，按引用出现的顺序排列
 */
export const IncremarkFootnotes: Component<IncremarkFootnotesProps> = () => {
  const { footnoteDefinitions, footnoteReferenceOrder } = useDefinationsContext()

  /**
   * 按引用顺序排列的脚注列表
   * 只显示已有定义的脚注
   */
  const orderedFootnotes = () => {
    return footnoteReferenceOrder()
      .map(identifier => ({
        identifier,
        definition: footnoteDefinitions()[identifier]
      }))
      .filter(item => item.definition !== undefined)
  }

  /**
   * 是否有脚注需要显示
   */
  const hasFootnotes = () => orderedFootnotes().length > 0

  return (
    <Show when={hasFootnotes()}>
      <section class="incremark-footnotes">
        <hr class="incremark-footnotes-divider" />
        <ol class="incremark-footnotes-list">
          <For each={orderedFootnotes()}>
            {(item, index) => (
              <li
                id={`fn-${item.identifier}`}
                class="incremark-footnote-item"
              >
                <div class="incremark-footnote-content">
                  {/* 脚注序号 */}
                  <span class="incremark-footnote-number">{index() + 1}.</span>

                  {/* 脚注内容 */}
                  <div class="incremark-footnote-body">
                    <For each={item.definition.children}>
                      {(child) => (
                        <IncremarkRenderer
                          node={(child as RootContent)}
                        />
                      )}
                    </For>
                  </div>
                </div>

                {/* 返回链接 */}
                <a
                  href={`#fnref-${item.identifier}`}
                  class="incremark-footnote-backref"
                  aria-label="返回引用位置"
                >
                  ↩
                </a>
              </li>
            )}
          </For>
        </ol>
      </section>
    </Show>
  )
}
