// packages/react/src/components/IncremarkBlockquote.tsx
import React from 'react'
import type { Blockquote } from 'mdast'
import type { ReactNode } from 'react'
import { IncremarkRenderer } from './IncremarkRenderer'

export interface IncremarkBlockquoteProps {
  node: Blockquote
  components?: Partial<Record<string, React.ComponentType<{ node: any }>>>
  customContainers?: Record<string, React.ComponentType<{ name: string; options?: Record<string, any>; children?: ReactNode }>>
  customCodeBlocks?: Record<string, React.ComponentType<{ codeStr: string; lang?: string; completed?: boolean; takeOver?: boolean }>>
  codeBlockConfigs?: Record<string, { takeOver?: boolean }>
  blockStatus?: 'pending' | 'stable' | 'completed'
}

export const IncremarkBlockquote: React.FC<IncremarkBlockquoteProps> = ({
  node,
  components,
  customContainers,
  customCodeBlocks,
  codeBlockConfigs,
  blockStatus
}) => {
  return (
    <blockquote className="incremark-blockquote">
      {node.children.map((child, index) => (
        <React.Fragment key={index}>
          <IncremarkRenderer
            node={child}
            components={components}
            customContainers={customContainers}
            customCodeBlocks={customCodeBlocks}
            codeBlockConfigs={codeBlockConfigs}
            blockStatus={blockStatus}
          />
        </React.Fragment>
      ))}
    </blockquote>
  )
}

// packages/solid/src/components/IncremarkBlockquote.tsx
/* @jsxImportSource solid-js */

import type { Blockquote } from 'mdast'
import { Component, For } from 'solid-js'
import type { ComponentMap, CodeBlockConfig } from '../types'
import { IncremarkRenderer } from './IncremarkRenderer'

export interface IncremarkBlockquoteProps {
  node: Blockquote
  components?: ComponentMap
  customContainers?: Record<string, Component<any>>
  customCodeBlocks?: Record<string, Component<any>>
  codeBlockConfigs?: Record<string, CodeBlockConfig>
  blockStatus?: 'pending' | 'stable' | 'completed'
}

export const IncremarkBlockquote: Component<IncremarkBlockquoteProps> = (props) => {
  return (
    <blockquote class="incremark-blockquote">
      <For each={props.node.children}>
        {(child) => (
          <IncremarkRenderer
            node={child}
            components={props.components}
            customContainers={props.customContainers}
            customCodeBlocks={props.customCodeBlocks}
            codeBlockConfigs={props.codeBlockConfigs}
            blockStatus={props.blockStatus}
          />
        )}
      </For>
    </blockquote>
  )
}
