// packages/svelte/src/components/Incremark.svelte
<!--
  @file Incremark.svelte - 主渲染组件
  @description 主入口组件，管理 blocks 渲染
-->

<script lang="ts">
  import type { Component } from 'svelte'
  import type { Readable } from 'svelte/store'
  import type { RootContent } from '@incremark/core'
  import type { HTML } from 'mdast'
  
  import { getDefinitionsContext } from '../context/definitionsContext'
  import type { UseIncremarkReturn } from '../stores/useIncremark'
  import type { ComponentMap, BlockWithStableId } from './types'
  
  // 导入默认组件
  import IncremarkParagraph from './IncremarkParagraph.svelte'
  import IncremarkHeading from './IncremarkHeading.svelte'
  import IncremarkCode from './IncremarkCode.svelte'
  import IncremarkList from './IncremarkList.svelte'
  import IncremarkTable from './IncremarkTable.svelte'
  import IncremarkBlockquote from './IncremarkBlockquote.svelte'
  import IncremarkThematicBreak from './IncremarkThematicBreak.svelte'
  import IncremarkMath from './IncremarkMath.svelte'
  import IncremarkHtmlElement from './IncremarkHtmlElement.svelte'
  import IncremarkDefault from './IncremarkDefault.svelte'
  import IncremarkFootnotes from './IncremarkFootnotes.svelte'
  import IncremarkRenderer from './IncremarkRenderer.svelte'

  /**
   * 检查是否是 html 节点
   */
  function isHtmlNode(node: RootContent): node is HTML {
    return node.type === 'html'
  }

  /**
   * 组件 Props
   */
  interface Props {
    /** 要渲染的块列表（来自 useIncremark 的 blocks） */
    blocks?: BlockWithStableId[] | Readable<BlockWithStableId[]>
    /** 自定义组件映射，key 为节点类型 */
    components?: ComponentMap
    /** 自定义容器组件映射，key 为容器名称（如 'warning', 'info'） */
    customContainers?: Record<string, Component<any>>
    /** 自定义代码块组件映射，key 为代码语言名称（如 'echart', 'mermaid'） */
    customCodeBlocks?: Record<string, Component<any>>
    /** 待处理块的样式类名 */
    pendingClass?: string
    /** 已完成块的样式类名 */
    completedClass?: string
    /** 是否显示块状态边框 */
    showBlockStatus?: boolean
    /** 可选：useIncremark 返回的对象（用于自动注入数据） */
    incremark?: UseIncremarkReturn
  }

  let {
    blocks = [],
    components = {},
    customContainers = {},
    customCodeBlocks = {},
    pendingClass = 'incremark-pending',
    completedClass = 'incremark-completed',
    showBlockStatus = false,
    incremark
  }: Props = $props()

  const context = getDefinitionsContext();
  const footnoteReferenceOrder = $derived(context?.footnoteReferenceOrder ?? []);

  // 计算 isDisplayComplete（当不使用 incremark 时）
  const actualIsDisplayComplete = $derived.by(() => {
    if (incremark) {
      // 如果提供了 incremark，在模板中直接使用 $incremark.isDisplayComplete
      return false
    }
    // 如果手动传入 blocks，自动判断是否所有 block 都是 completed
    const blocksArray = Array.isArray(blocks) ? blocks : []
    return blocksArray.length > 0 && blocksArray.every(b => b.status === 'completed')
  })

  // 默认组件映射
  const defaultComponents: ComponentMap = {
    paragraph: IncremarkParagraph,
    heading: IncremarkHeading,
    code: IncremarkCode,
    list: IncremarkList,
    table: IncremarkTable,
    blockquote: IncremarkBlockquote,
    thematicBreak: IncremarkThematicBreak,
    math: IncremarkMath,
    inlineMath: IncremarkMath,
    htmlElement: IncremarkHtmlElement
  }

  // 合并用户组件和默认组件
  const mergedComponents = $derived({
    ...defaultComponents,
    ...components
  })

  // 处理 blocks（可能是 store 或数组）
  const blocksArray = $derived.by(() => {
    if (incremark) {
      // 如果提供了 incremark，在模板中直接使用 incremark.blocks（store）
      return []
    }
    return Array.isArray(blocks) ? blocks : []
  })

  // 提取 incremark 的 stores（如果存在）
  const incremarkBlocks = $derived.by(() => incremark?.blocks)
  const incremarkIsDisplayComplete = $derived.by(() => incremark?.isDisplayComplete)
</script>

<div class="incremark">
  <!-- 主要内容块 -->
  {#if incremark && incremarkBlocks}
    <!-- 使用 incremark 的 blocks store -->
    {#each ($incremarkBlocks || []) as block (block.stableId)}
      {#if block.node.type !== 'definition' && block.node.type !== 'footnoteDefinition'}
        <div
          class="incremark-block {block.status === 'completed' ? completedClass : pendingClass} {showBlockStatus ? 'incremark-show-status' : ''} {(block as BlockWithStableId).isLastPending ? 'incremark-last-pending' : ''}"
        >
          <!-- 使用 IncremarkRenderer，传递 customContainers 和 customCodeBlocks -->
          <IncremarkRenderer 
            node={block.node} 
            customContainers={customContainers}
            customCodeBlocks={customCodeBlocks}
            blockStatus={block.status}
          />
        </div>
      {/if}
    {/each}
  {:else}
    <!-- 使用传入的 blocks 数组 -->
    {#each blocksArray as block (block.stableId)}
      {#if block.node.type !== 'definition' && block.node.type !== 'footnoteDefinition'}
        <div
          class="incremark-block {block.status === 'completed' ? completedClass : pendingClass} {showBlockStatus ? 'incremark-show-status' : ''} {block.isLastPending ? 'incremark-last-pending' : ''}"
        >
          <!-- 使用 IncremarkRenderer，传递 customContainers 和 customCodeBlocks -->
          <IncremarkRenderer 
            node={block.node} 
            customContainers={customContainers}
            customCodeBlocks={customCodeBlocks}
            blockStatus={block.status}
          />
        </div>
      {/if}
    {/each}
  {/if}

  <!-- 脚注列表（仅在内容完全显示后显示） -->
  {#if incremark && incremarkIsDisplayComplete && footnoteReferenceOrder && $incremarkIsDisplayComplete}
    {@const footnoteOrder = $footnoteReferenceOrder ?? []}
    {#if footnoteOrder.length > 0}
      <IncremarkFootnotes />
    {/if}
  {:else if !incremark && actualIsDisplayComplete && footnoteReferenceOrder}
    {@const footnoteOrder = $footnoteReferenceOrder ?? []}
    {#if footnoteOrder.length > 0}
      <IncremarkFootnotes />
    {/if}
  {/if}
</div>

// packages/vue/src/components/Incremark.vue
<script setup lang="ts">
import { computed, type Component } from 'vue'
import type { ParsedBlock, RootContent } from '@incremark/core'
import type { HTML } from 'mdast'
import { useDefinationsContext } from '../composables/useDefinationsContext'
import type { UseIncremarkReturn } from '../composables/useIncremark'
import IncremarkHeading from './IncremarkHeading.vue'
import IncremarkParagraph from './IncremarkParagraph.vue'
import IncremarkCode from './IncremarkCode.vue'
import IncremarkList from './IncremarkList.vue'
import IncremarkTable from './IncremarkTable.vue'
import IncremarkBlockquote from './IncremarkBlockquote.vue'
import IncremarkThematicBreak from './IncremarkThematicBreak.vue'
import IncremarkMath from './IncremarkMath.vue'
import IncremarkHtmlElement from './IncremarkHtmlElement.vue'
import IncremarkFootnotes from './IncremarkFootnotes.vue'
import IncremarkRenderer from './IncremarkRenderer.vue'

// 组件映射类型
export type ComponentMap = Partial<Record<string, Component>>

/**
 * 检查是否是 html 节点
 */
function isHtmlNode(node: RootContent): node is HTML {
  return node.type === 'html'
}

// 带稳定 ID 的块类型
export interface BlockWithStableId extends ParsedBlock {
  stableId: string
  isLastPending?: boolean // 是否是最后一个 pending 块
}

const props = withDefaults(
  defineProps<{
    /** 要渲染的块列表（来自 useIncremark 的 blocks） */
    blocks?: BlockWithStableId[]
    /** 自定义组件映射，key 为节点类型 */
    components?: ComponentMap
    /** 自定义容器组件映射，key 为容器名称（如 'warning', 'info'） */
    customContainers?: Record<string, Component>
    /** 自定义代码块组件映射，key 为代码语言名称（如 'echart', 'mermaid'） */
    customCodeBlocks?: Record<string, Component>
    /** 待处理块的样式类名 */
    pendingClass?: string
    /** 已完成块的样式类名 */
    completedClass?: string
    /** 是否显示块状态边框 */
    showBlockStatus?: boolean
    /** 可选：useIncremark 返回的对象（用于自动注入数据） */
    incremark?: UseIncremarkReturn
  }>(),
  {
    blocks: () => [],
    components: () => ({}),
    customContainers: () => ({}),
    customCodeBlocks: () => ({}),
    pendingClass: 'incremark-pending',
    completedClass: 'incremark-completed',
    showBlockStatus: false
  }
)

const {
  footnoteReferenceOrder
} = useDefinationsContext();

// 计算实际使用的 blocks 和 isDisplayComplete
const actualBlocks = computed<BlockWithStableId[]>(() => props.incremark?.blocks.value || props.blocks || [])
const actualIsDisplayComplete = computed(() => {
  if (props.incremark) {
    return props.incremark.isDisplayComplete.value
  }
  // 如果手动传入 blocks，自动判断是否所有 block 都是 completed
  const blocks = props.blocks || []
  return blocks.length > 0 && blocks.every(b => b.status === 'completed')
})

// 默认组件映射
const defaultComponents: Record<string, Component> = {
  heading: IncremarkHeading,
  paragraph: IncremarkParagraph,
  code: IncremarkCode,
  list: IncremarkList,
  table: IncremarkTable,
  blockquote: IncremarkBlockquote,
  thematicBreak: IncremarkThematicBreak,
  math: IncremarkMath,
  inlineMath: IncremarkMath,
  htmlElement: IncremarkHtmlElement
}

// 合并用户组件和默认组件
const mergedComponents = computed(() => ({
  ...defaultComponents,
  ...props.components
}))

</script>

<template>
  <div class="incremark">
    <!-- 主要内容块 -->
    <template v-for="block in actualBlocks">
      <div
        v-if="block.node.type !== 'definition' && block.node.type !== 'footnoteDefinition'"
        :key="block.stableId"
        :class="[
          'incremark-block',
          block.status === 'completed' ? completedClass : pendingClass,
          { 'incremark-show-status': showBlockStatus },
          { 'incremark-last-pending': block.isLastPending }
        ]"
      >
        <!-- HTML 节点：渲染为代码块显示源代码 -->
        <pre v-if="isHtmlNode(block.node)" class="incremark-html-code"><code>{{ (block.node as HTML).value }}</code></pre>
        <!-- 其他节点：使用对应组件，传递 customContainers 和 customCodeBlocks -->
        <IncremarkRenderer
          v-else
          :node="block.node"
          :block-status="block.status"
          :custom-containers="customContainers"
          :custom-code-blocks="customCodeBlocks"
        />
      </div>
    </template>

    <!-- 脚注列表（仅在内容完全显示后显示） -->
    <IncremarkFootnotes
      v-if="actualIsDisplayComplete && footnoteReferenceOrder.length > 0"
    />
  </div>
</template>
