// packages/solid/src/components/IncremarkContent.tsx
/* @jsxImportSource solid-js */

import { Component, createEffect, createMemo, onMount } from 'solid-js'
import type { JSX } from 'solid-js'
import { useIncremark } from '../composables/useIncremark'
import type { IncremarkContentProps } from '../types'
import Incremark from './Incremark'

/**
 * IncremarkContent 组件
 *
 * 全合一组件，自动处理流式和内容模式
 */
export const IncremarkContent: Component<IncremarkContentProps> = (props) => {
  const incremarkOptions = () => ({
    gfm: true,
    htmlTree: true,
    containers: true,
    math: true,
    ...props.incremarkOptions
  })

  const { blocks, append, finalize, render, reset, isDisplayComplete, markdown, contextValue, DefinationsProvider } = useIncremark(incremarkOptions)

  const isStreamMode = () => typeof props.stream === 'function'

  async function handleStreamInput() {
    if (!props.stream) return

    try {
      const stream = props.stream()

      for await (const chunk of stream) {
        append(chunk)
      }

      finalize()
    } catch (error) {
      console.error('Stream error: ', error)
      finalize()
    }
  }

  function handleContentInput(newContent?: string, oldContent?: string) {
    if (!newContent) {
      if (oldContent) {
        reset()
      }
      return
    }

    if (newContent?.startsWith(oldContent ?? '')) {
      const delta = newContent.slice((oldContent || '').length)
      append(delta)
    } else {
      render(newContent)
    }
  }

  // 监听 content 变化
  createEffect(() => {
    const newContent = props.content

    if (isStreamMode()) {
      handleStreamInput()
    } else {
      handleContentInput(newContent, markdown())
    }
  })

  // 监听 isFinished 变化
  createEffect(() => {
    const newIsFinished = props.isFinished
    if (newIsFinished && props.content === markdown()) {
      finalize()
    }
  })

  return (
    <DefinationsProvider value={contextValue}>
      <Incremark
        blocks={blocks}
        pendingClass={props.pendingClass}
        isDisplayComplete={isDisplayComplete()}
        showBlockStatus={props.showBlockStatus}
        components={props.components}
        customContainers={props.customContainers}
        customCodeBlocks={props.customCodeBlocks}
        codeBlockConfigs={props.codeBlockConfigs}
      />
    </DefinationsProvider>
  )
}

export default IncremarkContent

// packages/vue/src/components/IncremarkContent.vue
<script setup lang="ts">
  import { computed, watch } from 'vue';
  import { useIncremark } from '../composables';
  import { IncremarkContentProps } from '../types';
  import Incremark from './Incremark.vue';

  const props = defineProps<IncremarkContentProps>()

  const incremarkOptions = computed(() => ({
    gfm: true,
    htmlTree: true,
    containers: true,
    math: true,
    ...props.incremarkOptions
  }))

  const { blocks, append, finalize, render, reset, isDisplayComplete, markdown } = useIncremark(incremarkOptions);

  const isStreamMode = computed(() => typeof props.stream === 'function');

  async function handleStreamInput() {
    if (!props.stream) return;

    try {
      const stream = props.stream();

      for await (const chunk of stream) {
        append(chunk);
      } 

      finalize();
    } catch (error) {
      console.error('Stream error: ', error);
      finalize();
    }
  }

  function handleContentInput(newContent?: string, oldContent?: string) {
    if (!newContent) {
      if (oldContent) {
        reset();
      }
      return;
    }

    if (newContent?.startsWith(oldContent ?? '')) {
      const delta = newContent.slice((oldContent || '').length)
      append(delta);
    } else {
      render(newContent);
    }
  }

  watch(() => props.content, async (newContent, oldContent) => {
    if (isStreamMode.value) {
      await handleStreamInput();
    } else {
      handleContentInput(newContent, oldContent);
    }
  }, { immediate: true });

  watch(() => props.isFinished, (newIsFinished) => {
    if (newIsFinished && props.content === markdown.value) {
      finalize();
    }
  }, { immediate: true })
</script>

<template>
  <Incremark 
    :blocks="blocks"
    :pending-class="pendingClass"
    :is-display-complete="isDisplayComplete"
    :show-block-status="showBlockStatus"
    :components="components"
    :custom-containers="customContainers"
    :custom-code-blocks="customCodeBlocks"
    :code-block-configs="codeBlockConfigs"
  />
</template>
