// packages/react/src/components/IncremarkInline.tsx
import React from 'react'
import type { PhrasingContent, RootContent } from 'mdast'
import {
  type TextNodeWithChunks,
  hasChunks,
  getStableText,
  isHtmlNode
} from '@incremark/shared'
import { IncremarkHtmlElement, type HtmlElementNode } from './IncremarkHtmlElement'

export interface IncremarkInlineProps {
  nodes: PhrasingContent[]
}

/**
 * 类型守卫：检查是否是 htmlElement 节点
 */
function isHtmlElementNode(node: PhrasingContent): node is PhrasingContent & HtmlElementNode {
  return (node as unknown as HtmlElementNode).type === 'htmlElement'
}

/**
 * IncremarkInline 组件
 * 
 * 渲染行内内容（文本、加粗、斜体、链接等）
 * 
 * 注意：此组件与 Vue 版本保持完全一致的逻辑和结构
 */
export const IncremarkInline: React.FC<IncremarkInlineProps> = ({ nodes }) => {
  if (!nodes || nodes.length === 0) return null

  return (
    <>
      {nodes.map((node: PhrasingContent, i: number) => {
        // 文本节点（支持 chunks 渐入动画）
        if (node.type === 'text') {
          const textNode = node as TextNodeWithChunks
          if (hasChunks(node) && textNode.chunks && textNode.chunks.length > 0) {
            return (
              <React.Fragment key={i}>
                {getStableText(textNode)}
                {textNode.chunks.map((chunk: { createdAt: number; text: string }) => (
                  <span key={chunk.createdAt} className="incremark-fade-in">
                    {chunk.text}
                  </span>
                ))}
              </React.Fragment>
            )
          }
          return <React.Fragment key={i}>{(node as TextNodeWithChunks).value}</React.Fragment>
        }

        // htmlElement 节点（结构化的 HTML 元素）
        if (isHtmlElementNode(node)) {
          return <IncremarkHtmlElement key={i} node={node as unknown as HtmlElementNode} />
        }

        // HTML 节点（原始 HTML，如未启用 htmlTree 选项）
        if (isHtmlNode(node)) {
          // 使用 display: contents 的 span，避免影响布局
          return (
            <span
              key={i}
              style={{ display: 'contents' }}
              dangerouslySetInnerHTML={{ __html: node.value }}
            />
          )
        }

        // 加粗
        if (node.type === 'strong') {
          return (
            <strong key={i}>
              <IncremarkInline nodes={node.children as PhrasingContent[]} />
            </strong>
          )
        }

        // 斜体
        if (node.type === 'emphasis') {
          return (
            <em key={i}>
              <IncremarkInline nodes={node.children as PhrasingContent[]} />
            </em>
          )
        }

        // 行内代码
        if (node.type === 'inlineCode') {
          return (
            <code key={i} className="incremark-inline-code">
              {node.value}
            </code>
          )
        }

        // 链接
        if (node.type === 'link') {
          return (
            <a key={i} href={node.url} target="_blank" rel="noopener noreferrer">
              <IncremarkInline nodes={node.children as PhrasingContent[]} />
            </a>
          )
        }

        // 图片
        if (node.type === 'image') {
          return <img key={i} src={node.url} alt={node.alt || ''} loading="lazy" />
        }

        // 换行
        if (node.type === 'break') {
          return <br key={i} />
        }

        // 删除线
        if (node.type === 'delete') {
          return (
            <del key={i}>
              <IncremarkInline nodes={node.children as PhrasingContent[]} />
            </del>
          )
        }

        // 默认情况
        return <span key={i}>{(node as { value?: string }).value || ''}</span>
      })}
    </>
  )
}

// packages/vue/src/components/IncremarkInline.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { PhrasingContent, RootContent } from 'mdast'
import type { TextChunk } from '@incremark/core'
import {
  type TextNodeWithChunks,
  hasChunks,
  getStableText,
  isHtmlNode
} from '@incremark/shared'
import IncremarkMath from './IncremarkMath.vue'
import IncremarkHtmlElement from './IncremarkHtmlElement.vue'

// Math 节点类型
interface MathNode {
  type: 'math' | 'inlineMath'
  value: string
}

// HtmlElement 节点类型
interface HtmlElementNode {
  type: 'htmlElement'
  tagName: string
  attrs: Record<string, string>
  children: RootContent[]
}

/**
 * 类型守卫：检查是否是 htmlElement 节点
 */
function isHtmlElementNode(node: PhrasingContent): node is PhrasingContent & HtmlElementNode {
  return (node as unknown as HtmlElementNode).type === 'htmlElement'
}

const props = defineProps<{
  nodes: PhrasingContent[]
}>()

/**
 * 获取节点的 chunks（类型安全）
 */
function getChunks(node: PhrasingContent): TextChunk[] | undefined {
  if (hasChunks(node)) {
    return (node as TextNodeWithChunks).chunks
  }
  return undefined
}

/**
 * 类型守卫：检查是否是 inlineMath 节点
 * inlineMath 是 mdast-util-math 扩展的类型，不在标准 PhrasingContent 中
 */
function isInlineMath(node: PhrasingContent): node is PhrasingContent & MathNode {
  return (node as unknown as MathNode).type === 'inlineMath'
}

</script>

<template>
  <template v-for="(node, idx) in nodes" :key="idx">
    <!-- 文本（支持 chunks 渐入动画） -->
    <template v-if="node.type === 'text'">
      <!-- 稳定文本（已经显示过的部分，无动画） -->
      {{ getStableText(node as TextNodeWithChunks) }}
      <!-- 新增的 chunk 部分（带渐入动画） -->
      <span 
        v-for="chunk in getChunks(node)" 
        :key="chunk.createdAt"
        class="incremark-fade-in"
      >{{ chunk.text }}</span>
    </template>

    <!-- 行内公式 -->
    <IncremarkMath v-else-if="isInlineMath(node)" :node="(node as unknown as MathNode)" />

    <!-- htmlElement 节点（结构化的 HTML 元素） -->
    <IncremarkHtmlElement 
      v-else-if="isHtmlElementNode(node)" 
      :node="(node as unknown as HtmlElementNode)" 
    />

    <!-- HTML 节点（原始 HTML，如未启用 htmlTree 选项） -->
    <span v-else-if="isHtmlNode(node)" style="display: contents;" v-html="(node as any).value"></span>

    <!-- 加粗 -->
    <strong v-else-if="node.type === 'strong'">
      <IncremarkInline :nodes="(node.children as PhrasingContent[])" />
    </strong>

    <!-- 斜体 -->
    <em v-else-if="node.type === 'emphasis'">
      <IncremarkInline :nodes="(node.children as PhrasingContent[])" />
    </em>

    <!-- 行内代码 -->
    <code v-else-if="node.type === 'inlineCode'" class="incremark-inline-code">{{ (node as any).value }}</code>

    <!-- 链接 -->
    <a
      v-else-if="node.type === 'link'"
      :href="node.url"
      target="_blank"
      rel="noopener noreferrer"
    >
      <IncremarkInline :nodes="(node.children as PhrasingContent[])" />
    </a>

    <!-- 图片 -->
    <img
      v-else-if="node.type === 'image'"
      :src="node.url"
      :alt="node.alt || ''"
      loading="lazy"
    />

    <!-- 换行 -->
    <br v-else-if="node.type === 'break'" />

    <!-- 删除线 -->
    <del v-else-if="node.type === 'delete'">
      <IncremarkInline :nodes="(node.children as PhrasingContent[])" />
    </del>
  </template>
</template>
