// packages/react/src/components/IncremarkList.tsx
import React from 'react'
import type { List, ListItem, PhrasingContent } from 'mdast'
import { IncremarkInline } from './IncremarkInline'

export interface IncremarkListProps {
  node: List
}

function getItemContent(item: ListItem): PhrasingContent[] {
  const firstChild = item.children[0]
  if (firstChild?.type === 'paragraph') {
    return firstChild.children as PhrasingContent[]
  }
  return []
}

export const IncremarkList: React.FC<IncremarkListProps> = ({ node }) => {
  const Tag = node.ordered ? 'ol' : 'ul'
  const isTaskList = node.children?.some(item => item.checked !== null && item.checked !== undefined)
  
  return (
    <Tag className={`incremark-list ${isTaskList ? 'task-list' : ''}`}>
      {node.children?.map((item, index) => {
        const isTaskItem = item.checked !== null && item.checked !== undefined
        const content = getItemContent(item)
        
        if (isTaskItem) {
          return (
            <li key={index} className="incremark-list-item task-item">
              <label className="task-label">
                <input 
                  type="checkbox" 
                  checked={item.checked || false} 
                  disabled 
                  className="checkbox"
                />
                <span className="task-content">
                  <IncremarkInline nodes={content} />
                </span>
              </label>
            </li>
          )
        }
        
        return (
          <li key={index} className="incremark-list-item">
            <IncremarkInline nodes={content} />
          </li>
        )
      })}
    </Tag>
  )
}

// packages/vue/src/components/IncremarkList.vue
<script setup lang="ts">
import type { List, ListItem, PhrasingContent } from 'mdast'
import { computed } from 'vue'
import IncremarkInline from './IncremarkInline.vue'

const props = defineProps<{
  node: List
}>()

const tag = computed(() => props.node.ordered ? 'ol' : 'ul')

function getItemContent(item: ListItem): PhrasingContent[] {
  const firstChild = item.children[0]
  if (firstChild?.type === 'paragraph') {
    return firstChild.children as PhrasingContent[]
  }
  return []
}
</script>

<template>
  <component :is="tag" class="incremark-list" :class="{ 'task-list': node.children.some(item => item.checked !== null && item.checked !== undefined) }">
    <li 
      v-for="(item, index) in node.children" 
      :key="index" 
      class="incremark-list-item"
      :class="{ 'task-item': item.checked !== null && item.checked !== undefined }"
    >
      <label v-if="item.checked !== null && item.checked !== undefined" class="task-label">
        <input 
          type="checkbox" 
          :checked="item.checked" 
          disabled 
          class="checkbox"
        />
        <span class="task-content">
          <IncremarkInline :nodes="getItemContent(item)" />
        </span>
      </label>
      <template v-else>
        <IncremarkInline :nodes="getItemContent(item)" />
      </template>
    </li>
  </component>
</template>
