// examples/vue/src/components/CustomInfoContainer.vue
<script setup lang="ts">
defineProps<{
  name: string
  options?: Record<string, any>
}>()
</script>

<template>
  <div class="custom-info-container">
    <div class="custom-info-header">
      <span class="custom-info-icon">ℹ️</span>
      <span v-if="options?.title" class="custom-info-title">{{ options.title }}</span>
      <span v-else class="custom-info-title">信息</span>
    </div>
    <div class="custom-info-content">
      <slot />
    </div>
  </div>
</template>

<!-- 样式已移动到共享的 styles.css -->

// examples/react/src/components/CustomInfoContainer.tsx
import React from 'react'

export interface CustomInfoContainerProps {
  name: string
  options?: Record<string, any>
  children?: React.ReactNode
}

export const CustomInfoContainer: React.FC<CustomInfoContainerProps> = ({ options, children }) => {
  return (
    <div className="custom-info-container">
      <div className="custom-info-header">
        <span className="custom-info-icon">ℹ️</span>
        <span className="custom-info-title">
          {options?.title || '信息'}
        </span>
      </div>
      <div className="custom-info-content">
        {children}
      </div>
    </div>
  )
}
