// examples/vue/src/components/CustomHeading.vue
<script setup lang="ts">
import type { Heading, PhrasingContent } from 'mdast'
import { IncremarkInline } from '@incremark/vue'

defineProps<{
  node: Heading
}>()
</script>

<template>
  <component :is="`h${node.depth}`" class="custom-heading">
    ✨ <IncremarkInline :nodes="(node.children as PhrasingContent[])" />
  </component>
</template>

<!-- 样式已移动到共享的 styles.css -->

// examples/react/src/components/CustomHeading.tsx
import React from 'react'
import type { Heading, PhrasingContent } from 'mdast'
import { IncremarkInline } from '@incremark/react'

export interface CustomHeadingProps {
  node: Heading
}

export const CustomHeading: React.FC<CustomHeadingProps> = ({ node }) => {
  const Tag = `h${node.depth}` as keyof JSX.IntrinsicElements
  return (
    <Tag className="custom-heading">
      ✨ <IncremarkInline nodes={node.children as PhrasingContent[]} />
    </Tag>
  )
}
